"""
FastAPI service for the SHACL Validation Agent.

Validates OWL/RDF ontologies against SHACL quality shapes.
Accepts raw ontology text or fetches from the Ontology API by job_id.

Endpoints
---------
GET  /health
POST /validate                  validate ontology text → {job_id}
GET  /jobs/{job_id}             poll status + summary
GET  /jobs/{job_id}/report      full validation report (violations, warnings, suggestions)
GET  /list                      list all validation jobs
"""
from __future__ import annotations

import logging
import os
import sys
import threading
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

import httpx
from fastapi import BackgroundTasks, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).parent))

from shacl_agent import SHACLAgent, SHACLConfig

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ── Upstream service URLs ──────────────────────────────────────────────────────
ONTOLOGY_API_URL = os.environ.get("ONTOLOGY_API_URL", "http://localhost:8001")

# ── In-memory job store ────────────────────────────────────────────────────────
_jobs: Dict[str, Dict] = {}
_lock = threading.Lock()

# ── App ────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="SHACL Validation API",
    version="1.0.0",
    description=(
        "Validates OWL/RDF ontologies generated by the Ontology Agent against "
        "SHACL quality shapes.  Returns a quality label (PASS/WARN/FAIL), "
        "per-shape violation details, and actionable suggestions."
    ),
    docs_url="/docs",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic models ────────────────────────────────────────────────────────────

class ValidateRequest(BaseModel):
    """
    Provide *either* ontology_text (raw Turtle/XML/N3) *or* ontology_job_id
    (a job_id from the Ontology API — the service fetches the content itself).
    """
    ontology_text:      Optional[str] = None
    ontology_job_id:    Optional[str] = None   # fetch from Ontology API
    ontology_format:    str  = "auto"           # "auto"|"turtle"|"xml"|"n3"
    extra_shapes_ttl:   str  = ""               # additional SHACL shapes (Turtle)
    min_coverage:       float = 0.5
    check_orphan_classes: bool = True
    check_namespace:    bool  = True


class JobStatusResponse(BaseModel):
    job_id:           str
    status:           str
    quality:          Optional[str] = None
    violation_count:  Optional[int] = None
    warning_count:    Optional[int] = None
    semantic_issue_count: Optional[int] = None
    ontology_stats:   Optional[Dict[str, Any]] = None
    error:            Optional[str] = None


# ── Helpers ────────────────────────────────────────────────────────────────────

def _job_status_response(job_id: str, job: Dict) -> JobStatusResponse:
    summary = job.get("summary", {})
    return JobStatusResponse(
        job_id           = job_id,
        status           = job["status"],
        quality          = summary.get("quality"),
        violation_count  = summary.get("violation_count"),
        warning_count    = summary.get("warning_count"),
        semantic_issue_count = summary.get("semantic_issue_count"),
        ontology_stats   = summary.get("ontology_stats"),
        error            = job.get("error"),
    )


async def _fetch_ontology_from_job(job_id: str) -> str:
    """Fetch ontology text from the Ontology API."""
    url = f"{ONTOLOGY_API_URL}/jobs/{job_id}/content"
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.get(url)
    if resp.status_code != 200:
        raise HTTPException(
            status_code=502,
            detail=f"Ontology API returned {resp.status_code} for job {job_id}: {resp.text[:200]}",
        )
    data = resp.json()
    text = data.get("content", "")
    if not text:
        raise HTTPException(status_code=404, detail=f"Ontology job {job_id} has no content yet.")
    return text


# ── Background worker ──────────────────────────────────────────────────────────

def _run_validation(job_id: str, ontology_text: str, req: ValidateRequest) -> None:
    with _lock:
        _jobs[job_id]["status"] = "running"

    try:
        config = SHACLConfig(
            ontology_format       = req.ontology_format,
            extra_shapes_ttl      = req.extra_shapes_ttl or "",
            min_coverage          = req.min_coverage,
            check_orphan_classes  = req.check_orphan_classes,
            check_namespace       = req.check_namespace,
        )
        agent  = SHACLAgent(config)
        result = agent.run(ontology_text)

        with _lock:
            _jobs[job_id].update({
                "status":  "done",
                "summary": result.get("summary", {}),
                "quality": result.get("quality"),
                "phase":   result.get("phase"),
                "errors":  result.get("errors", []),
            })
        logger.info(
            "SHACL job %s done — quality=%s violations=%s",
            job_id,
            result.get("quality"),
            result.get("summary", {}).get("violation_count"),
        )

    except Exception as exc:
        logger.exception("SHACL job %s failed", job_id)
        with _lock:
            _jobs[job_id].update({"status": "error", "error": str(exc)})


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok", "service": "shacl-validation-api"}


@app.post("/validate", summary="Submit ontology for SHACL validation")
async def validate(req: ValidateRequest, background_tasks: BackgroundTasks):
    """
    Submit an ontology for SHACL validation.  Returns immediately with a
    job_id; poll `GET /jobs/{job_id}` for status and results.

    Supply **ontology_text** (raw Turtle/XML/N3 string) **or**
    **ontology_job_id** (a job_id from the Ontology API — fetched automatically).
    """
    # Resolve ontology text
    if req.ontology_job_id and not req.ontology_text:
        ontology_text = await _fetch_ontology_from_job(req.ontology_job_id)
    elif req.ontology_text:
        ontology_text = req.ontology_text
    else:
        raise HTTPException(
            status_code=422,
            detail="Provide either 'ontology_text' or 'ontology_job_id'.",
        )

    job_id = str(uuid.uuid4())
    with _lock:
        _jobs[job_id] = {
            "status":  "queued",
            "summary": {},
            "quality": None,
            "error":   None,
        }

    background_tasks.add_task(_run_validation, job_id, ontology_text, req)
    logger.info("SHACL job %s queued", job_id)
    return {"job_id": job_id, "status": "queued"}


@app.get("/jobs/{job_id}", response_model=JobStatusResponse, summary="Poll validation job status")
def get_job(job_id: str):
    with _lock:
        job = _jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    return _job_status_response(job_id, job)


@app.get("/jobs/{job_id}/report", summary="Full validation report")
def get_report(job_id: str):
    """
    Returns the complete validation report once the job is done:
      - quality         : "PASS" | "WARN" | "FAIL"
      - ontology_stats  : {classes, datatype_props, object_props, triples, …}
      - violations      : list of SHACL sh:Violation entries
      - warnings        : list of SHACL sh:Warning entries
      - semantic_issues : Python-detected issues (orphans, low coverage, …)
      - shacl_by_shape  : violation/warning counts grouped by shape name
      - semantic_by_check: issue counts grouped by check name
      - suggestions     : actionable remediation suggestions
      - pipeline_errors : non-fatal pipeline errors
    """
    with _lock:
        job = _jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    if job["status"] not in ("done", "error"):
        raise HTTPException(status_code=409, detail=f"Job '{job_id}' is still {job['status']}.")
    if job["status"] == "error":
        raise HTTPException(status_code=500, detail=job.get("error", "Unknown error"))
    return job.get("summary", {})


@app.get("/list", summary="List all validation jobs")
def list_jobs():
    with _lock:
        return [
            {
                "job_id":  jid,
                "status":  j["status"],
                "quality": j.get("quality"),
                "violations": j.get("summary", {}).get("violation_count"),
            }
            for jid, j in _jobs.items()
        ]


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("SHACL_API_PORT", 8006))
    uvicorn.run("shacl_api:app", host="0.0.0.0", port=port, reload=False)
