apiVersion: v1
kind: ConfigMap
metadata:
  name: datananite-config
  namespace: datananite2
data:
  LOG_LEVEL: "info"
  DIALOG_ENV: "production"
  UNSTRUCTURED_WORKERS: "4"
  DATA_DIR: "/data/reports"
  GLOSSARY_DB: "/data/reports/glossary.db"
  METADATA_DB: "/data/metadata.db"
  KG_STORE_DB: "/data/kg_store.db"
  UNSTRUCTURED_DB: "/data/unstructured.db"
  METADATA_API_URL: "http://agent-api-service:8000"
  ONTOLOGY_API_URL: "http://ontology-api-service:8001"
  KG_API_URL: "http://kg-api-service:8002"
  DIALOG_API_URL: "http://dialog-api-service:8003"
  CONFORMITY_API_URL: "http://conformity-api-service:8004"
  SHACL_API_URL: "http://shacl-api-service:8007"
  UNSTRUCTURED_API_URL: "http://unstructured-api-service:8008"
  UNSTRUCTURED_PUBLIC_URL: "http://datananite2.endpoints.cog01k24f1ea555zdv7ynzthxanz5.cloud.goog/api/unstructured"
  ORCHESTRATOR_URL: "http://chat-ui-service:8005"
