-- =============================================================================
--  PNC Insurance Data Warehouse
--  Target : PNC_DW schema  (PNC source schema is NEVER modified)
--  23 Dimensions + 20 Facts + 4 Analytical Views
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. SCHEMA
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS PNC_DW
    COMMENT = 'P&C Insurance Star-Schema DW over PNC source schema';

-- ---------------------------------------------------------------------------
-- 1. SEQUENCES
-- ---------------------------------------------------------------------------
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_DATE_SK              START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_POLICYHOLDER_SK      START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_POLICY_SK            START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_AGENT_SK             START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_ADJUSTER_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_UNDERWRITER_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_PROPERTY_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_VEHICLE_SK           START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_COVERAGE_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_REINSURER_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_GEOGRAPHY_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_PERIL_SK             START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_BENEFICIARY_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_DOC_TYPE_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_PAY_METHOD_SK        START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_INV_TYPE_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_COMP_REG_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_CLAIM_TYPE_SK        START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FRAUD_LEVEL_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_DIST_CHAN_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_POLICY_TYPE_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_AUDIT_ACTION_SK      START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_COV_STATUS_SK        START = 1 INCREMENT = 1;

CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_CLAIMS_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_PREMIUMS_SK     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_PAYMENTS_SK     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_ASSESS_SK       START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_RISK_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_FRAUD_SK        START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_INV_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_DED_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_COMP_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_REIN_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_LOSS_SK         START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_DOC_SK          START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_AUDIT_SK        START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_BENEF_SK        START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_COV_UTIL_SK     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_ADJ_MON_SK      START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_AGT_MON_SK      START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_POL_LIFE_SK     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_REIN_REC_SK     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE PNC_DW.SEQ_FACT_PROP_RISK_SK    START = 1 INCREMENT = 1;

-- =============================================================================
-- DIMENSION DDL
-- =============================================================================

-- 1. DIM_DATE
CREATE OR REPLACE TABLE PNC_DW.DIM_DATE (
    DATE_SK         INTEGER       NOT NULL PRIMARY KEY,
    FULL_DATE       DATE          NOT NULL UNIQUE,
    DAY_OF_MONTH    TINYINT       NOT NULL,
    DAY_NAME        VARCHAR(10)   NOT NULL,
    DAY_OF_WEEK     TINYINT       NOT NULL,
    IS_WEEKEND      BOOLEAN       NOT NULL,
    WEEK_OF_YEAR    TINYINT       NOT NULL,
    MONTH           TINYINT       NOT NULL,
    MONTH_NAME      VARCHAR(10)   NOT NULL,
    QUARTER         TINYINT       NOT NULL,
    YEAR            SMALLINT      NOT NULL,
    FISCAL_YEAR     SMALLINT      NOT NULL,
    FISCAL_QUARTER  TINYINT       NOT NULL,
    IS_MONTH_END    BOOLEAN       NOT NULL,
    IS_QUARTER_END  BOOLEAN       NOT NULL,
    IS_YEAR_END     BOOLEAN       NOT NULL
);

-- 2. DIM_POLICYHOLDER
CREATE OR REPLACE TABLE PNC_DW.DIM_POLICYHOLDER (
    POLICYHOLDER_SK   INTEGER       NOT NULL PRIMARY KEY,
    POLICYHOLDER_ID   VARCHAR(50)   NOT NULL UNIQUE,
    FULL_NAME         VARCHAR(200),
    EMAIL             VARCHAR(200),
    PHONE             VARCHAR(50),
    ADDRESS           VARCHAR(500),
    CITY              VARCHAR(100),
    STATE             VARCHAR(50),
    ZIP               VARCHAR(20),
    DOB               DATE,
    AGE_BAND          VARCHAR(20),
    MARITAL_STATUS    VARCHAR(50),
    EMPLOYMENT_STATUS VARCHAR(50),
    ANNUAL_INCOME     NUMBER(18,2),
    INCOME_BAND       VARCHAR(30),
    CREDIT_RATING     VARCHAR(20),
    CREDIT_SCORE      NUMBER(5),
    CREDIT_BAND       VARCHAR(20),
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. DIM_POLICY
CREATE OR REPLACE TABLE PNC_DW.DIM_POLICY (
    POLICY_SK             INTEGER       NOT NULL PRIMARY KEY,
    POLICY_ID             VARCHAR(50)   NOT NULL UNIQUE,
    POLICYHOLDER_SK       INTEGER,
    AGENT_SK              INTEGER,
    POLICY_TYPE           VARCHAR(100),
    STATUS                VARCHAR(50),
    POLICY_TIER           VARCHAR(50),
    BUSINESS_TYPE         VARCHAR(100),
    EFFECTIVE_DATE        DATE,
    EXPIRATION_DATE       DATE,
    POLICY_DURATION_DAYS  INTEGER,
    PAYMENT_FREQUENCY     VARCHAR(50),
    DISTRIBUTION_CHANNEL  VARCHAR(100),
    ANNUAL_PREMIUM        NUMBER(18,2),
    COVERAGE_LIMIT        NUMBER(18,2),
    DISCOUNT_RATE         NUMBER(8,4),
    MULTI_POLICY_FLAG     BOOLEAN,
    DW_CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. DIM_AGENT
CREATE OR REPLACE TABLE PNC_DW.DIM_AGENT (
    AGENT_SK           INTEGER       NOT NULL PRIMARY KEY,
    AGENT_ID           VARCHAR(50)   NOT NULL UNIQUE,
    FULL_NAME          VARCHAR(200),
    EMAIL              VARCHAR(200),
    PHONE              VARCHAR(50),
    AGENT_TYPE         VARCHAR(100),
    SPECIALTY          VARCHAR(200),
    STATE_LICENSE      VARCHAR(50),
    LICENSE_NUMBER     VARCHAR(100),
    YEARS_EXPERIENCE   INTEGER,
    ANNUAL_COMMISSION  NUMBER(18,2),
    POLICIES_MANAGED   INTEGER,
    RETENTION_RATE     NUMBER(8,4),
    STATUS             VARCHAR(50),
    APPOINTMENT_DATE   DATE,
    DW_CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. DIM_ADJUSTER
CREATE OR REPLACE TABLE PNC_DW.DIM_ADJUSTER (
    ADJUSTER_SK          INTEGER       NOT NULL PRIMARY KEY,
    ADJUSTER_ID          VARCHAR(50)   NOT NULL UNIQUE,
    FULL_NAME            VARCHAR(200),
    EMAIL                VARCHAR(200),
    ADJUSTER_TYPE        VARCHAR(100),
    SPECIALTY            VARCHAR(200),
    YEARS_EXPERIENCE     INTEGER,
    LICENSE              VARCHAR(100),
    TERRITORY            VARCHAR(200),
    STATUS               VARCHAR(50),
    ACTIVE_CLAIMS        INTEGER,
    ANNUAL_COMPENSATION  NUMBER(18,2),
    SETTLEMENT_RATE      NUMBER(8,4),
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. DIM_UNDERWRITER
CREATE OR REPLACE TABLE PNC_DW.DIM_UNDERWRITER (
    UNDERWRITER_SK    INTEGER       NOT NULL PRIMARY KEY,
    UNDERWRITER_ID    VARCHAR(50)   NOT NULL UNIQUE,
    FULL_NAME         VARCHAR(200),
    EMAIL             VARCHAR(200),
    TITLE             VARCHAR(100),
    SPECIALTY         VARCHAR(200),
    YEARS_EXPERIENCE  INTEGER,
    CERTIFICATION     VARCHAR(200),
    OFFICE_LOCATION   VARCHAR(200),
    STATUS            VARCHAR(50),
    HIRE_DATE         DATE,
    POLICIES_WRITTEN  INTEGER,
    SALARY            NUMBER(18,2),
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. DIM_PROPERTY
CREATE OR REPLACE TABLE PNC_DW.DIM_PROPERTY (
    PROPERTY_SK        INTEGER       NOT NULL PRIMARY KEY,
    PROPERTY_ID        VARCHAR(50)   NOT NULL UNIQUE,
    POLICY_ID          VARCHAR(50),
    PROPERTY_TYPE      VARCHAR(100),
    ADDRESS            VARCHAR(500),
    CITY               VARCHAR(100),
    STATE              VARCHAR(50),
    ZIP                VARCHAR(20),
    YEAR_BUILT         SMALLINT,
    SQUARE_FOOTAGE     NUMBER(10,2),
    CONSTRUCTION_TYPE  VARCHAR(100),
    ROOF_TYPE          VARCHAR(100),
    REPLACEMENT_COST   NUMBER(18,2),
    MARKET_VALUE       NUMBER(18,2),
    CONDITION          VARCHAR(50),
    SPRINKLER_SYSTEM   BOOLEAN,
    SECURITY_SYSTEM    BOOLEAN,
    FLOOD_ZONE         VARCHAR(50),
    DW_CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. DIM_VEHICLE
CREATE OR REPLACE TABLE PNC_DW.DIM_VEHICLE (
    VEHICLE_SK         INTEGER       NOT NULL PRIMARY KEY,
    VEHICLE_ID         VARCHAR(50)   NOT NULL UNIQUE,
    POLICY_ID          VARCHAR(50),
    MAKE               VARCHAR(100),
    MODEL              VARCHAR(100),
    YEAR               SMALLINT,
    VIN                VARCHAR(50),
    BODY_TYPE          VARCHAR(100),
    USE_TYPE           VARCHAR(100),
    MILEAGE            INTEGER,
    ACTUAL_CASH_VALUE  NUMBER(18,2),
    CONDITION          VARCHAR(50),
    ANTI_THEFT_DEVICE  BOOLEAN,
    AIRBAGS            BOOLEAN,
    BACKUP_CAMERA      BOOLEAN,
    REGISTERED_STATE   VARCHAR(50),
    STATUS             VARCHAR(50),
    DW_CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 9. DIM_COVERAGE
CREATE OR REPLACE TABLE PNC_DW.DIM_COVERAGE (
    COVERAGE_SK         INTEGER       NOT NULL PRIMARY KEY,
    COVERAGE_ID         VARCHAR(50)   NOT NULL UNIQUE,
    POLICY_ID           VARCHAR(50),
    COVERAGE_TYPE       VARCHAR(100),
    COVERAGE_LIMIT      NUMBER(18,2),
    SUB_LIMIT           NUMBER(18,2),
    DEDUCTIBLE_AMOUNT   NUMBER(18,2),
    COVERAGE_STATUS     VARCHAR(50),
    VALUATION_METHOD    VARCHAR(100),
    ENDORSEMENT_STATUS  VARCHAR(100),
    EFFECTIVE_DATE      DATE,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 10. DIM_REINSURER
CREATE OR REPLACE TABLE PNC_DW.DIM_REINSURER (
    REINSURER_SK         INTEGER       NOT NULL PRIMARY KEY,
    REINSURER_NAME       VARCHAR(300)  NOT NULL UNIQUE,
    REINSURER_RATING     VARCHAR(20),
    COMMON_TREATY_TYPE   VARCHAR(100),
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 11. DIM_GEOGRAPHY
CREATE OR REPLACE TABLE PNC_DW.DIM_GEOGRAPHY (
    GEOGRAPHY_SK           INTEGER      NOT NULL PRIMARY KEY,
    STATE_CODE             VARCHAR(5)   NOT NULL UNIQUE,
    STATE_NAME             VARCHAR(100),
    REGION                 VARCHAR(50),
    IS_CATASTROPHE_PRONE   BOOLEAN,
    DW_CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 12. DIM_PERIL
CREATE OR REPLACE TABLE PNC_DW.DIM_PERIL (
    PERIL_SK              INTEGER       NOT NULL PRIMARY KEY,
    PERIL_TYPE            VARCHAR(200)  NOT NULL UNIQUE,
    PERIL_CATEGORY        VARCHAR(100),
    IS_CATASTROPHE_PERIL  BOOLEAN,
    DW_CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 13. DIM_BENEFICIARY
CREATE OR REPLACE TABLE PNC_DW.DIM_BENEFICIARY (
    BENEFICIARY_SK    INTEGER       NOT NULL PRIMARY KEY,
    BENEFICIARY_ID    VARCHAR(50)   NOT NULL UNIQUE,
    POLICY_ID         VARCHAR(50),
    FULL_NAME         VARCHAR(200),
    EMAIL             VARCHAR(200),
    PHONE             VARCHAR(50),
    RELATIONSHIP      VARCHAR(100),
    BENEFICIARY_TYPE  VARCHAR(100),
    DOB               DATE,
    STATUS            VARCHAR(50),
    DESIGNATION_DATE  DATE,
    MINOR_FLAG        BOOLEAN,
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 14. DIM_DOCUMENT_TYPE  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_DOCUMENT_TYPE (
    DOCUMENT_TYPE_SK  INTEGER       NOT NULL PRIMARY KEY,
    DOCUMENT_TYPE     VARCHAR(200),
    DOCUMENT_CATEGORY VARCHAR(200),
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 15. DIM_PAYMENT_METHOD  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_PAYMENT_METHOD (
    PAYMENT_METHOD_SK  INTEGER       NOT NULL PRIMARY KEY,
    PAYMENT_METHOD     VARCHAR(100)  NOT NULL UNIQUE,
    DW_CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 16. DIM_INVESTIGATION_TYPE  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_INVESTIGATION_TYPE (
    INVESTIGATION_TYPE_SK  INTEGER       NOT NULL PRIMARY KEY,
    INVESTIGATION_TYPE     VARCHAR(200)  NOT NULL UNIQUE,
    DW_CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 17. DIM_COMPLIANCE_REGULATION  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_COMPLIANCE_REGULATION (
    COMPLIANCE_REGULATION_SK  INTEGER       NOT NULL PRIMARY KEY,
    REGULATION                VARCHAR(300),
    JURISDICTION              VARCHAR(200),
    DW_CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 18. DIM_CLAIM_TYPE  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_CLAIM_TYPE (
    CLAIM_TYPE_SK   INTEGER       NOT NULL PRIMARY KEY,
    CLAIM_TYPE      VARCHAR(100),
    CLAIMANT_TYPE   VARCHAR(100),
    DW_CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 19. DIM_FRAUD_RISK_LEVEL  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_FRAUD_RISK_LEVEL (
    FRAUD_RISK_LEVEL_SK  INTEGER       NOT NULL PRIMARY KEY,
    FRAUD_RISK_LEVEL     VARCHAR(50),
    PRIMARY_INDICATOR    VARCHAR(200),
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 20. DIM_DISTRIBUTION_CHANNEL  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_DISTRIBUTION_CHANNEL (
    DISTRIBUTION_CHANNEL_SK  INTEGER       NOT NULL PRIMARY KEY,
    DISTRIBUTION_CHANNEL     VARCHAR(100),
    POLICY_TIER              VARCHAR(50),
    DW_CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 21. DIM_POLICY_TYPE  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_POLICY_TYPE (
    POLICY_TYPE_SK  INTEGER       NOT NULL PRIMARY KEY,
    POLICY_TYPE     VARCHAR(100),
    BUSINESS_TYPE   VARCHAR(100),
    DW_CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 22. DIM_AUDIT_ACTION  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_AUDIT_ACTION (
    AUDIT_ACTION_SK   INTEGER       NOT NULL PRIMARY KEY,
    ACTION            VARCHAR(100),
    OPERATION_TYPE    VARCHAR(100),
    USER_ROLE         VARCHAR(100),
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 23. DIM_COVERAGE_STATUS  (lookup)
CREATE OR REPLACE TABLE PNC_DW.DIM_COVERAGE_STATUS (
    COVERAGE_STATUS_SK  INTEGER       NOT NULL PRIMARY KEY,
    COVERAGE_STATUS     VARCHAR(50),
    VALUATION_METHOD    VARCHAR(100),
    ENDORSEMENT_STATUS  VARCHAR(100),
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- FACT DDL
-- =============================================================================

-- 1. FACT_CLAIMS
CREATE OR REPLACE TABLE PNC_DW.FACT_CLAIMS (
    CLAIM_SK              INTEGER       NOT NULL PRIMARY KEY,
    CLAIM_ID              VARCHAR(50)   NOT NULL,
    POLICY_SK             INTEGER,
    POLICYHOLDER_SK       INTEGER,
    ADJUSTER_SK           INTEGER,
    AGENT_SK              INTEGER,
    CLAIM_TYPE_SK         INTEGER,
    FRAUD_RISK_LEVEL_SK   INTEGER,
    DATE_FILED_SK         INTEGER,
    DATE_CLOSED_SK        INTEGER,
    CLAIM_STATUS          VARCHAR(100),
    SEVERITY              VARCHAR(50),
    REPORTING_METHOD      VARCHAR(100),
    LITIGATION_FLAG       BOOLEAN,
    SUBROGATION_FLAG      BOOLEAN,
    HAS_FRAUD_INDICATOR   BOOLEAN,
    FRAUD_SCORE           NUMBER(8,4),
    CLAIMED_AMOUNT        NUMBER(18,2),
    APPROVED_AMOUNT       NUMBER(18,2),
    DEDUCTIBLE_APPLIED    NUMBER(18,2),
    NET_APPROVED_AMOUNT   NUMBER(18,2),
    TOTAL_PAID_AMOUNT     NUMBER(18,2),
    CLAIM_RECOVERY_PCT    NUMBER(8,4),
    DAYS_TO_CLOSE         INTEGER,
    DW_CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. FACT_PREMIUMS
CREATE OR REPLACE TABLE PNC_DW.FACT_PREMIUMS (
    PREMIUM_SK             INTEGER       NOT NULL PRIMARY KEY,
    PREMIUM_ID             VARCHAR(50)   NOT NULL,
    POLICY_SK              INTEGER,
    POLICYHOLDER_SK        INTEGER,
    AGENT_SK               INTEGER,
    PAYMENT_METHOD_SK      INTEGER,
    PREMIUM_START_DATE_SK  INTEGER,
    PREMIUM_END_DATE_SK    INTEGER,
    LAST_PAYMENT_DATE_SK   INTEGER,
    PAYMENT_SCHEDULE       VARCHAR(50),
    PAYMENT_STATUS         VARCHAR(50),
    AUTOPAY_ENROLLED       BOOLEAN,
    BASE_PREMIUM           NUMBER(18,2),
    DISCOUNT_AMOUNT        NUMBER(18,2),
    SURCHARGE_AMOUNT       NUMBER(18,2),
    FINAL_PREMIUM          NUMBER(18,2),
    LATE_FEE               NUMBER(18,2),
    INSTALLMENT_FEE        NUMBER(18,2),
    TOTAL_BILLED           NUMBER(18,2),
    NET_DISCOUNT_RATE      NUMBER(8,4),
    DW_CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. FACT_CLAIM_PAYMENTS
CREATE OR REPLACE TABLE PNC_DW.FACT_CLAIM_PAYMENTS (
    PAYMENT_SK          INTEGER       NOT NULL PRIMARY KEY,
    PAYMENT_ID          VARCHAR(50)   NOT NULL,
    CLAIM_ID            VARCHAR(50)   NOT NULL,
    POLICY_SK           INTEGER,
    POLICYHOLDER_SK     INTEGER,
    PAYMENT_METHOD_SK   INTEGER,
    PAYMENT_DATE_SK     INTEGER,
    PAYMENT_TYPE        VARCHAR(100),
    PAYMENT_STATUS      VARCHAR(100),
    PAYEE_TYPE          VARCHAR(100),
    CURRENCY            VARCHAR(10),
    TAX_WITHHELD_FLAG   BOOLEAN,
    ISSUED_1099_FLAG    BOOLEAN,
    REFERENCE_NUMBER    VARCHAR(100),
    PAYMENT_AMOUNT      NUMBER(18,2),
    WITHHOLDING_AMOUNT  NUMBER(18,2),
    NET_PAYMENT         NUMBER(18,2),
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. FACT_CLAIM_ASSESSMENT
CREATE OR REPLACE TABLE PNC_DW.FACT_CLAIM_ASSESSMENT (
    ASSESSMENT_SK           INTEGER       NOT NULL PRIMARY KEY,
    ASSESSMENT_ID           VARCHAR(50)   NOT NULL,
    CLAIM_ID                VARCHAR(50)   NOT NULL,
    POLICY_SK               INTEGER,
    ADJUSTER_SK             INTEGER,
    ASSESSMENT_DATE_SK      INTEGER,
    ASSESSMENT_METHOD       VARCHAR(100),
    RECOMMENDATION          VARCHAR(200),
    EVIDENCE_STRENGTH       VARCHAR(50),
    COMPLEXITY_LEVEL        VARCHAR(50),
    DOCUMENTATION_STATUS    VARCHAR(100),
    EXPERT_CONSULTED        BOOLEAN,
    ESTIMATED_LOSS          NUMBER(18,2),
    RECOMMENDED_PAYOUT      NUMBER(18,2),
    SALVAGE_VALUE           NUMBER(18,2),
    HOURS_SPENT             NUMBER(10,2),
    REVISION_COUNT          INTEGER,
    ASSESSMENT_ACCURACY_PCT NUMBER(8,4),
    DW_CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. FACT_RISK_UNDERWRITING
CREATE OR REPLACE TABLE PNC_DW.FACT_RISK_UNDERWRITING (
    RISK_SK                INTEGER       NOT NULL PRIMARY KEY,
    RISK_PROFILE_ID        VARCHAR(50)   NOT NULL,
    POLICY_SK              INTEGER,
    POLICYHOLDER_SK        INTEGER,
    UNDERWRITER_SK         INTEGER,
    ASSESSMENT_DATE_SK     INTEGER,
    RISK_CATEGORY          VARCHAR(100),
    UNDERWRITING_DECISION  VARCHAR(100),
    RATE_CLASS             VARCHAR(50),
    PRIOR_CLAIMS_FLAG      BOOLEAN,
    HIGH_VALUE_FLAG        BOOLEAN,
    CATASTROPHE_EXPOSURE   VARCHAR(50),
    REVIEW_FREQUENCY       VARCHAR(50),
    RISK_SCORE             NUMBER(10,4),
    LOSS_PROBABILITY       NUMBER(8,6),
    RATE_MODIFIER          NUMBER(8,4),
    EXPECTED_LOSS_AMOUNT   NUMBER(18,2),
    DW_CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. FACT_FRAUD_DETECTION
CREATE OR REPLACE TABLE PNC_DW.FACT_FRAUD_DETECTION (
    FRAUD_SK                  INTEGER       NOT NULL PRIMARY KEY,
    FRAUD_INDICATOR_ID        VARCHAR(50)   NOT NULL,
    CLAIM_ID                  VARCHAR(50)   NOT NULL,
    POLICY_SK                 INTEGER,
    FRAUD_RISK_LEVEL_SK       INTEGER,
    DETECTION_DATE_SK         INTEGER,
    DETECTION_METHOD          VARCHAR(200),
    INVESTIGATION_STATUS      VARCHAR(100),
    LAW_ENFORCEMENT_NOTIFIED  BOOLEAN,
    PROSECUTION_FLAG          BOOLEAN,
    SIU_ASSIGNED              BOOLEAN,
    FRAUD_SCORE               NUMBER(8,4),
    ESTIMATED_FRAUD_AMOUNT    NUMBER(18,2),
    DW_CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. FACT_INVESTIGATION
CREATE OR REPLACE TABLE PNC_DW.FACT_INVESTIGATION (
    INVESTIGATION_SK       INTEGER       NOT NULL PRIMARY KEY,
    INVESTIGATION_ID       VARCHAR(50)   NOT NULL,
    CLAIM_ID               VARCHAR(50)   NOT NULL,
    POLICY_SK              INTEGER,
    INVESTIGATION_TYPE_SK  INTEGER,
    START_DATE_SK          INTEGER,
    END_DATE_SK            INTEGER,
    STATUS                 VARCHAR(50),
    LEAD_INVESTIGATOR      VARCHAR(200),
    OUTCOME                VARCHAR(200),
    SURVEILLANCE_CONDUCTED BOOLEAN,
    LEGAL_HOLD             BOOLEAN,
    COURT_SUBPOENA         BOOLEAN,
    PRIORITY               VARCHAR(50),
    INVESTIGATION_COST     NUMBER(18,2),
    DURATION_DAYS          INTEGER,
    DW_CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. FACT_DEDUCTIBLE_TRACKING
CREATE OR REPLACE TABLE PNC_DW.FACT_DEDUCTIBLE_TRACKING (
    DEDUCTIBLE_SK         INTEGER       NOT NULL PRIMARY KEY,
    DEDUCTIBLE_ID         VARCHAR(50)   NOT NULL,
    CLAIM_ID              VARCHAR(50)   NOT NULL,
    COVERAGE_SK           INTEGER,
    POLICY_SK             INTEGER,
    APPLIED_DATE_SK       INTEGER,
    STATUS                VARCHAR(50),
    DEDUCTIBLE_TYPE       VARCHAR(100),
    DEDUCTIBLE_STRUCTURE  VARCHAR(100),
    WAIVER_APPROVED       BOOLEAN,
    SCHEDULED_DEDUCTIBLE  NUMBER(18,2),
    APPLIED_AMOUNT        NUMBER(18,2),
    WAIVED_AMOUNT         NUMBER(18,2),
    NET_DEDUCTIBLE        NUMBER(18,2),
    DW_CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 9. FACT_COMPLIANCE
CREATE OR REPLACE TABLE PNC_DW.FACT_COMPLIANCE (
    COMPLIANCE_SK               INTEGER       NOT NULL PRIMARY KEY,
    COMPLIANCE_ID               VARCHAR(50)   NOT NULL,
    POLICY_SK                   INTEGER,
    COMPLIANCE_REGULATION_SK    INTEGER,
    EFFECTIVE_DATE_SK           INTEGER,
    EXPIRY_DATE_SK              INTEGER,
    LAST_REVIEW_DATE_SK         INTEGER,
    COMPLIANCE_STATUS           VARCHAR(100),
    RISK_LEVEL                  VARCHAR(50),
    AUDIT_RESULT                VARCHAR(100),
    REVIEW_TYPE                 VARCHAR(100),
    REMEDIATION_STATUS          VARCHAR(100),
    REPORTED_TO_REGULATOR       BOOLEAN,
    PENALTY_AMOUNT              NUMBER(18,2),
    DW_CREATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 10. FACT_REINSURANCE
CREATE OR REPLACE TABLE PNC_DW.FACT_REINSURANCE (
    REINSURANCE_SK      INTEGER       NOT NULL PRIMARY KEY,
    REINSURANCE_ID      VARCHAR(50)   NOT NULL,
    POLICY_SK           INTEGER,
    REINSURER_SK        INTEGER,
    TREATY_START_SK     INTEGER,
    TREATY_END_SK       INTEGER,
    TREATY_TYPE         VARCHAR(100),
    TREATY_STATUS       VARCHAR(50),
    CLAIMS_CEDED_FLAG   BOOLEAN,
    CESSION_PERCENTAGE  NUMBER(8,4),
    CEDED_LIMIT         NUMBER(18,2),
    RETAINED_LIMIT      NUMBER(18,2),
    REINSURANCE_PREMIUM NUMBER(18,2),
    COMMISSION_RATE     NUMBER(8,4),
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 11. FACT_LOSS_EVENT
CREATE OR REPLACE TABLE PNC_DW.FACT_LOSS_EVENT (
    LOSS_EVENT_SK           INTEGER       NOT NULL PRIMARY KEY,
    EVENT_ID                VARCHAR(50)   NOT NULL,
    CLAIM_ID                VARCHAR(50)   NOT NULL,
    POLICY_SK               INTEGER,
    PERIL_SK                INTEGER,
    GEOGRAPHY_SK            INTEGER,
    EVENT_DATE_SK           INTEGER,
    PROPERTY_TYPE           VARCHAR(100),
    SEVERITY_LEVEL          VARCHAR(50),
    EVENT_STATUS            VARCHAR(50),
    CAT_EVENT_FLAG          BOOLEAN,
    CAT_EVENT_CODE          VARCHAR(50),
    RESPONSIBLE_PARTY       VARCHAR(200),
    ESTIMATED_DAMAGE        NUMBER(18,2),
    DURATION_DAYS           INTEGER,
    PROPERTIES_AFFECTED     INTEGER,
    TOTAL_INDUSTRY_LOSS_EST NUMBER(18,2),
    DW_CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 12. FACT_DOCUMENT_ACTIVITY
CREATE OR REPLACE TABLE PNC_DW.FACT_DOCUMENT_ACTIVITY (
    DOCUMENT_SK       INTEGER       NOT NULL PRIMARY KEY,
    DOCUMENT_ID       VARCHAR(50)   NOT NULL,
    REFERENCE_ID      VARCHAR(50),
    REFERENCE_TYPE    VARCHAR(100),
    DOCUMENT_TYPE_SK  INTEGER,
    UPLOAD_DATE_SK    INTEGER,
    DOCUMENT_STATUS   VARCHAR(100),
    FILE_FORMAT       VARCHAR(50),
    STORAGE_PATH      VARCHAR(500),
    VERIFIED          BOOLEAN,
    CONFIDENTIAL      BOOLEAN,
    FILE_SIZE_MB      NUMBER(12,4),
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 13. FACT_AUDIT_LOG
CREATE OR REPLACE TABLE PNC_DW.FACT_AUDIT_LOG (
    AUDIT_SK          INTEGER       NOT NULL PRIMARY KEY,
    AUDIT_ID          VARCHAR(50)   NOT NULL,
    AUDIT_ACTION_SK   INTEGER,
    EVENT_DATE_SK     INTEGER,
    TABLE_NAME        VARCHAR(200),
    RECORD_ID         VARCHAR(200),
    USER_ID           VARCHAR(200),
    IP_ADDRESS        VARCHAR(50),
    ACTION_STATUS     VARCHAR(50),
    REGULATORY_EVENT  VARCHAR(200),
    CHANGE_DESCRIPTION VARCHAR(1000),
    EVENT_COUNT       INTEGER       DEFAULT 1,
    DW_CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 14. FACT_BENEFICIARY
CREATE OR REPLACE TABLE PNC_DW.FACT_BENEFICIARY (
    BENEFICIARY_FACT_SK  INTEGER       NOT NULL PRIMARY KEY,
    BENEFICIARY_SK       INTEGER,
    POLICY_SK            INTEGER,
    DESIGNATION_DATE_SK  INTEGER,
    STATUS               VARCHAR(50),
    MINOR_FLAG           BOOLEAN,
    BENEFIT_PERCENTAGE   NUMBER(8,4),
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 15. FACT_COVERAGE_UTILIZATION
CREATE OR REPLACE TABLE PNC_DW.FACT_COVERAGE_UTILIZATION (
    COVERAGE_UTIL_SK         INTEGER       NOT NULL PRIMARY KEY,
    COVERAGE_SK              INTEGER,
    POLICY_SK                INTEGER,
    COVERAGE_STATUS_SK       INTEGER,
    EFFECTIVE_DATE_SK        INTEGER,
    COVERAGE_LIMIT           NUMBER(18,2),
    SUB_LIMIT                NUMBER(18,2),
    DEDUCTIBLE_AMOUNT        NUMBER(18,2),
    APPLIED_DEDUCTIBLE_TOTAL NUMBER(18,2),
    WAIVED_DEDUCTIBLE_TOTAL  NUMBER(18,2),
    UTILIZATION_PCT          NUMBER(8,4),
    DW_CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 16. FACT_ADJUSTER_MONTHLY_SNAPSHOT
CREATE OR REPLACE TABLE PNC_DW.FACT_ADJUSTER_MONTHLY_SNAPSHOT (
    ADJUSTER_MONTHLY_SK  INTEGER     NOT NULL PRIMARY KEY,
    ADJUSTER_SK          INTEGER,
    SNAPSHOT_YEAR        SMALLINT    NOT NULL,
    SNAPSHOT_MONTH       TINYINT     NOT NULL,
    CLAIMS_HANDLED       INTEGER,
    AVG_DAYS_TO_CLOSE    NUMBER(10,2),
    TOTAL_APPROVED       NUMBER(18,2),
    ASSESSMENTS_DONE     INTEGER,
    TOTAL_HOURS_SPENT    NUMBER(12,2),
    AVG_REVISION_COUNT   NUMBER(8,2),
    LITIGATION_COUNT     INTEGER,
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 17. FACT_AGENT_PERFORMANCE_MONTHLY
CREATE OR REPLACE TABLE PNC_DW.FACT_AGENT_PERFORMANCE_MONTHLY (
    AGENT_MONTHLY_SK         INTEGER     NOT NULL PRIMARY KEY,
    AGENT_SK                 INTEGER,
    SNAPSHOT_YEAR            SMALLINT    NOT NULL,
    SNAPSHOT_MONTH           TINYINT     NOT NULL,
    POLICIES_WRITTEN         INTEGER,
    NEW_POLICIES             INTEGER,
    TOTAL_PREMIUM_COLLECTED  NUMBER(18,2),
    AVG_DISCOUNT_RATE        NUMBER(8,4),
    TOTAL_DISCOUNTS_GIVEN    NUMBER(18,2),
    TOTAL_LATE_FEES          NUMBER(18,2),
    DW_CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 18. FACT_POLICY_LIFECYCLE
CREATE OR REPLACE TABLE PNC_DW.FACT_POLICY_LIFECYCLE (
    POLICY_LIFECYCLE_SK   INTEGER       NOT NULL PRIMARY KEY,
    POLICY_SK             INTEGER,
    POLICYHOLDER_SK       INTEGER,
    AGENT_SK              INTEGER,
    POLICY_TYPE_SK        INTEGER,
    DISTRIBUTION_CHAN_SK  INTEGER,
    EFFECTIVE_DATE_SK     INTEGER,
    EXPIRATION_DATE_SK    INTEGER,
    IS_ACTIVE             BOOLEAN,
    IS_EXPIRED            BOOLEAN,
    MULTI_POLICY_FLAG     BOOLEAN,
    POLICY_DURATION_DAYS  INTEGER,
    ANNUAL_PREMIUM        NUMBER(18,2),
    COVERAGE_LIMIT        NUMBER(18,2),
    DISCOUNT_RATE         NUMBER(8,4),
    DW_CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 19. FACT_CLAIM_REINSURANCE_RECOVERY
CREATE OR REPLACE TABLE PNC_DW.FACT_CLAIM_REINSURANCE_RECOVERY (
    CLAIM_REIN_RECOVERY_SK  INTEGER       NOT NULL PRIMARY KEY,
    CLAIM_ID                VARCHAR(50)   NOT NULL,
    REINSURANCE_ID          VARCHAR(50)   NOT NULL,
    POLICY_SK               INTEGER,
    REINSURER_SK            INTEGER,
    DATE_FILED_SK           INTEGER,
    CLAIM_STATUS            VARCHAR(100),
    TREATY_TYPE             VARCHAR(100),
    CESSION_PERCENTAGE      NUMBER(8,4),
    CLAIM_APPROVED_AMOUNT   NUMBER(18,2),
    CEDED_RECOVERY          NUMBER(18,2),
    RETAINED_AMOUNT         NUMBER(18,2),
    DW_CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 20. FACT_PROPERTY_RISK_EXPOSURE
CREATE OR REPLACE TABLE PNC_DW.FACT_PROPERTY_RISK_EXPOSURE (
    PROPERTY_RISK_SK     INTEGER       NOT NULL PRIMARY KEY,
    PROPERTY_SK          INTEGER,
    POLICY_SK            INTEGER,
    POLICYHOLDER_SK      INTEGER,
    UNDERWRITER_SK       INTEGER,
    GEOGRAPHY_SK         INTEGER,
    ASSESSMENT_DATE_SK   INTEGER,
    FLOOD_ZONE           VARCHAR(50),
    IS_HIGH_FLOOD_RISK   BOOLEAN,
    SPRINKLER_SYSTEM     BOOLEAN,
    SECURITY_SYSTEM      BOOLEAN,
    CONSTRUCTION_TYPE    VARCHAR(100),
    RISK_CATEGORY        VARCHAR(100),
    CATASTROPHE_EXPOSURE VARCHAR(50),
    REPLACEMENT_COST     NUMBER(18,2),
    MARKET_VALUE         NUMBER(18,2),
    RISK_SCORE           NUMBER(10,4),
    LOSS_PROBABILITY     NUMBER(8,6),
    EXPECTED_LOSS_AMOUNT NUMBER(18,2),
    RISK_TO_VALUE_RATIO  NUMBER(8,6),
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- LOAD DIMENSIONS
-- =============================================================================

-- 1. DIM_DATE (2015-01-01 to 2030-12-31)
INSERT INTO PNC_DW.DIM_DATE
    (DATE_SK, FULL_DATE, DAY_OF_MONTH, DAY_NAME, DAY_OF_WEEK, IS_WEEKEND,
     WEEK_OF_YEAR, MONTH, MONTH_NAME, QUARTER, YEAR,
     FISCAL_YEAR, FISCAL_QUARTER, IS_MONTH_END, IS_QUARTER_END, IS_YEAR_END)
WITH spine AS (
    SELECT DATEADD(DAY, SEQ4(), '2015-01-01'::DATE) AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 5844))
)
SELECT
    ROW_NUMBER() OVER (ORDER BY d)                                  AS DATE_SK,
    d                                                               AS FULL_DATE,
    DAY(d)                                                          AS DAY_OF_MONTH,
    DAYNAME(d)                                                      AS DAY_NAME,
    CASE DAYOFWEEK(d) WHEN 0 THEN 7 ELSE DAYOFWEEK(d) END          AS DAY_OF_WEEK,
    DAYOFWEEK(d) IN (0, 6)                                          AS IS_WEEKEND,
    WEEKOFYEAR(d)                                                   AS WEEK_OF_YEAR,
    MONTH(d)                                                        AS MONTH,
    MONTHNAME(d)                                                    AS MONTH_NAME,
    QUARTER(d)                                                      AS QUARTER,
    YEAR(d)                                                         AS YEAR,
    YEAR(d)                                                         AS FISCAL_YEAR,
    QUARTER(d)                                                      AS FISCAL_QUARTER,
    d = LAST_DAY(d)                                                 AS IS_MONTH_END,
    d = LAST_DAY(d) AND MONTH(d) IN (3,6,9,12)                     AS IS_QUARTER_END,
    MONTH(d) = 12 AND d = LAST_DAY(d)                               AS IS_YEAR_END
FROM spine;

-- 2. DIM_POLICYHOLDER
INSERT INTO PNC_DW.DIM_POLICYHOLDER
    (POLICYHOLDER_SK, POLICYHOLDER_ID, FULL_NAME, EMAIL, PHONE,
     ADDRESS, CITY, STATE, ZIP, DOB, AGE_BAND,
     MARITAL_STATUS, EMPLOYMENT_STATUS,
     ANNUAL_INCOME, INCOME_BAND, CREDIT_RATING, CREDIT_SCORE, CREDIT_BAND)
SELECT
    PNC_DW.SEQ_POLICYHOLDER_SK.NEXTVAL,
    POLICYHOLDER_ID,
    TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')),
    EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP,
    TRY_TO_DATE(DOB::VARCHAR),
    CASE
        WHEN DATEDIFF(YEAR, TRY_TO_DATE(DOB::VARCHAR), CURRENT_DATE()) < 25  THEN '<25'
        WHEN DATEDIFF(YEAR, TRY_TO_DATE(DOB::VARCHAR), CURRENT_DATE()) < 35  THEN '25-34'
        WHEN DATEDIFF(YEAR, TRY_TO_DATE(DOB::VARCHAR), CURRENT_DATE()) < 45  THEN '35-44'
        WHEN DATEDIFF(YEAR, TRY_TO_DATE(DOB::VARCHAR), CURRENT_DATE()) < 55  THEN '45-54'
        WHEN DATEDIFF(YEAR, TRY_TO_DATE(DOB::VARCHAR), CURRENT_DATE()) < 65  THEN '55-64'
        ELSE '65+'
    END,
    MARITAL_STATUS, EMPLOYMENT_STATUS,
    ANNUAL_INCOME,
    CASE
        WHEN ANNUAL_INCOME < 30000  THEN '<30k'
        WHEN ANNUAL_INCOME < 60000  THEN '30-60k'
        WHEN ANNUAL_INCOME < 100000 THEN '60-100k'
        WHEN ANNUAL_INCOME < 200000 THEN '100-200k'
        ELSE '>200k'
    END,
    CREDIT_RATING, CREDIT_SCORE,
    CASE
        WHEN CREDIT_SCORE < 580 THEN 'Poor'
        WHEN CREDIT_SCORE < 670 THEN 'Fair'
        WHEN CREDIT_SCORE < 740 THEN 'Good'
        WHEN CREDIT_SCORE < 800 THEN 'Very Good'
        ELSE 'Excellent'
    END
FROM PNC.POLICYHOLDER;

-- 3. DIM_AGENT
INSERT INTO PNC_DW.DIM_AGENT
    (AGENT_SK, AGENT_ID, FULL_NAME, EMAIL, PHONE,
     AGENT_TYPE, SPECIALTY, STATE_LICENSE, LICENSE_NUMBER,
     YEARS_EXPERIENCE, ANNUAL_COMMISSION, POLICIES_MANAGED,
     RETENTION_RATE, STATUS, APPOINTMENT_DATE)
SELECT
    PNC_DW.SEQ_AGENT_SK.NEXTVAL,
    AGENT_ID,
    TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')),
    EMAIL, PHONE, AGENT_TYPE, SPECIALTY, STATE_LICENSE, LICENSE_NUMBER,
    YEARS_EXPERIENCE, ANNUAL_COMMISSION, POLICIES_MANAGED,
    RETENTION_RATE, STATUS,
    TRY_TO_DATE(APPOINTMENT_DATE::VARCHAR)
FROM PNC.AGENT;

-- 4. DIM_POLICY  (needs POLICYHOLDER_SK + AGENT_SK — load after 2 and 3)
INSERT INTO PNC_DW.DIM_POLICY
    (POLICY_SK, POLICY_ID, POLICYHOLDER_SK, AGENT_SK,
     POLICY_TYPE, STATUS, POLICY_TIER, BUSINESS_TYPE,
     EFFECTIVE_DATE, EXPIRATION_DATE, POLICY_DURATION_DAYS,
     PAYMENT_FREQUENCY, DISTRIBUTION_CHANNEL,
     ANNUAL_PREMIUM, COVERAGE_LIMIT, DISCOUNT_RATE, MULTI_POLICY_FLAG)
SELECT
    PNC_DW.SEQ_POLICY_SK.NEXTVAL,
    p.POLICY_ID,
    dph.POLICYHOLDER_SK,
    dag.AGENT_SK,
    p.POLICY_TYPE, p.STATUS, p.POLICY_TIER, p.BUSINESS_TYPE,
    TRY_TO_DATE(p.EFFECTIVE_DATE::VARCHAR),
    TRY_TO_DATE(p.EXPIRATION_DATE::VARCHAR),
    DATEDIFF(DAY,
             TRY_TO_DATE(p.EFFECTIVE_DATE::VARCHAR),
             TRY_TO_DATE(p.EXPIRATION_DATE::VARCHAR)),
    p.PAYMENT_FREQUENCY, p.DISTRIBUTION_CHANNEL,
    p.ANNUAL_PREMIUM, p.COVERAGE_LIMIT, p.DISCOUNT_RATE,
    p.MULTI_POLICY_FLAG::BOOLEAN
FROM PNC.POLICY p
LEFT JOIN PNC_DW.DIM_POLICYHOLDER dph ON dph.POLICYHOLDER_ID = p.POLICYHOLDER_ID
LEFT JOIN PNC_DW.DIM_AGENT        dag ON dag.AGENT_ID         = p.AGENT_ID;

-- 5. DIM_ADJUSTER
INSERT INTO PNC_DW.DIM_ADJUSTER
    (ADJUSTER_SK, ADJUSTER_ID, FULL_NAME, EMAIL,
     ADJUSTER_TYPE, SPECIALTY, YEARS_EXPERIENCE, LICENSE,
     TERRITORY, STATUS, ACTIVE_CLAIMS, ANNUAL_COMPENSATION, SETTLEMENT_RATE)
SELECT
    PNC_DW.SEQ_ADJUSTER_SK.NEXTVAL,
    ADJUSTER_ID,
    TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')),
    EMAIL, ADJUSTER_TYPE, SPECIALTY, YEARS_EXPERIENCE, LICENSE,
    TERRITORY, STATUS, ACTIVE_CLAIMS, ANNUAL_COMPENSATION, SETTLEMENT_RATE
FROM PNC.ADJUSTER;

-- 6. DIM_UNDERWRITER
INSERT INTO PNC_DW.DIM_UNDERWRITER
    (UNDERWRITER_SK, UNDERWRITER_ID, FULL_NAME, EMAIL,
     TITLE, SPECIALTY, YEARS_EXPERIENCE, CERTIFICATION,
     OFFICE_LOCATION, STATUS, HIRE_DATE, POLICIES_WRITTEN, SALARY)
SELECT
    PNC_DW.SEQ_UNDERWRITER_SK.NEXTVAL,
    UNDERWRITER_ID,
    TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')),
    EMAIL, TITLE, SPECIALTY, YEARS_EXPERIENCE, CERTIFICATION,
    OFFICE_LOCATION, STATUS,
    TRY_TO_DATE(HIRE_DATE::VARCHAR),
    POLICIES_WRITTEN, SALARY
FROM PNC.UNDERWRITER;

-- 7. DIM_PROPERTY
INSERT INTO PNC_DW.DIM_PROPERTY
    (PROPERTY_SK, PROPERTY_ID, POLICY_ID, PROPERTY_TYPE,
     ADDRESS, CITY, STATE, ZIP,
     YEAR_BUILT, SQUARE_FOOTAGE, CONSTRUCTION_TYPE, ROOF_TYPE,
     REPLACEMENT_COST, MARKET_VALUE, CONDITION,
     SPRINKLER_SYSTEM, SECURITY_SYSTEM, FLOOD_ZONE)
SELECT
    PNC_DW.SEQ_PROPERTY_SK.NEXTVAL,
    PROPERTY_ID, POLICY_ID, PROPERTY_TYPE,
    ADDRESS, CITY, STATE, ZIP,
    YEAR_BUILT::SMALLINT, SQUARE_FOOTAGE, CONSTRUCTION_TYPE, ROOF_TYPE,
    REPLACEMENT_COST, MARKET_VALUE, CONDITION,
    SPRINKLER_SYSTEM::BOOLEAN, SECURITY_SYSTEM::BOOLEAN, FLOOD_ZONE
FROM PNC.PROPERTY;

-- 8. DIM_VEHICLE
INSERT INTO PNC_DW.DIM_VEHICLE
    (VEHICLE_SK, VEHICLE_ID, POLICY_ID, MAKE, MODEL, YEAR, VIN,
     BODY_TYPE, USE_TYPE, MILEAGE, ACTUAL_CASH_VALUE, CONDITION,
     ANTI_THEFT_DEVICE, AIRBAGS, BACKUP_CAMERA, REGISTERED_STATE, STATUS)
SELECT
    PNC_DW.SEQ_VEHICLE_SK.NEXTVAL,
    VEHICLE_ID, POLICY_ID, MAKE, MODEL, YEAR::SMALLINT, VIN,
    BODY_TYPE, USE_TYPE, MILEAGE, ACTUAL_CASH_VALUE, CONDITION,
    ANTI_THEFT_DEVICE::BOOLEAN, AIRBAGS::BOOLEAN, BACKUP_CAMERA::BOOLEAN,
    REGISTERED_STATE, STATUS
FROM PNC.VEHICLE;

-- 9. DIM_COVERAGE
INSERT INTO PNC_DW.DIM_COVERAGE
    (COVERAGE_SK, COVERAGE_ID, POLICY_ID, COVERAGE_TYPE,
     COVERAGE_LIMIT, SUB_LIMIT, DEDUCTIBLE_AMOUNT,
     COVERAGE_STATUS, VALUATION_METHOD, ENDORSEMENT_STATUS, EFFECTIVE_DATE)
SELECT
    PNC_DW.SEQ_COVERAGE_SK.NEXTVAL,
    COVERAGE_ID, POLICY_ID, COVERAGE_TYPE,
    COVERAGE_LIMIT, SUB_LIMIT, DEDUCTIBLE_AMOUNT,
    COVERAGE_STATUS, VALUATION_METHOD, ENDORSEMENT_STATUS,
    TRY_TO_DATE(EFFECTIVE_DATE::VARCHAR)
FROM PNC.COVERAGE;

-- 10. DIM_REINSURER
INSERT INTO PNC_DW.DIM_REINSURER
    (REINSURER_SK, REINSURER_NAME, REINSURER_RATING, COMMON_TREATY_TYPE)
WITH agg AS (
    SELECT
        REINSURER_NAME,
        MAX(REINSURER_RATING)  AS REINSURER_RATING,
        MODE(TREATY_TYPE)      AS COMMON_TREATY_TYPE
    FROM PNC.REINSURANCE
    WHERE REINSURER_NAME IS NOT NULL
    GROUP BY REINSURER_NAME
)
SELECT
    PNC_DW.SEQ_REINSURER_SK.NEXTVAL,
    REINSURER_NAME,
    REINSURER_RATING,
    COMMON_TREATY_TYPE
FROM agg;

-- 11. DIM_GEOGRAPHY
INSERT INTO PNC_DW.DIM_GEOGRAPHY
    (GEOGRAPHY_SK, STATE_CODE, STATE_NAME, REGION, IS_CATASTROPHE_PRONE)
WITH all_states AS (
    SELECT UPPER(TRIM(STATE)) AS S FROM PNC.POLICYHOLDER WHERE STATE IS NOT NULL
    UNION SELECT UPPER(TRIM(STATE)) FROM PNC.PROPERTY    WHERE STATE IS NOT NULL
    UNION SELECT UPPER(TRIM(STATE)) FROM PNC.LOSS_EVENT  WHERE STATE IS NOT NULL
),
u AS (SELECT DISTINCT S AS STATE_CODE FROM all_states WHERE S <> '')
SELECT
    PNC_DW.SEQ_GEOGRAPHY_SK.NEXTVAL,
    STATE_CODE,
    NULL::VARCHAR AS STATE_NAME,
    CASE STATE_CODE
        WHEN 'ME' THEN 'Northeast' WHEN 'NH' THEN 'Northeast' WHEN 'VT' THEN 'Northeast'
        WHEN 'MA' THEN 'Northeast' WHEN 'RI' THEN 'Northeast' WHEN 'CT' THEN 'Northeast'
        WHEN 'NY' THEN 'Northeast' WHEN 'NJ' THEN 'Northeast' WHEN 'PA' THEN 'Northeast'
        WHEN 'MD' THEN 'Southeast' WHEN 'DE' THEN 'Southeast' WHEN 'VA' THEN 'Southeast'
        WHEN 'WV' THEN 'Southeast' WHEN 'NC' THEN 'Southeast' WHEN 'SC' THEN 'Southeast'
        WHEN 'GA' THEN 'Southeast' WHEN 'FL' THEN 'Southeast' WHEN 'AL' THEN 'Southeast'
        WHEN 'MS' THEN 'Southeast' WHEN 'TN' THEN 'Southeast' WHEN 'KY' THEN 'Southeast'
        WHEN 'AR' THEN 'Southeast' WHEN 'LA' THEN 'Southeast'
        WHEN 'OH' THEN 'Midwest'   WHEN 'MI' THEN 'Midwest'   WHEN 'IN' THEN 'Midwest'
        WHEN 'IL' THEN 'Midwest'   WHEN 'WI' THEN 'Midwest'   WHEN 'MN' THEN 'Midwest'
        WHEN 'IA' THEN 'Midwest'   WHEN 'MO' THEN 'Midwest'   WHEN 'ND' THEN 'Midwest'
        WHEN 'SD' THEN 'Midwest'   WHEN 'NE' THEN 'Midwest'   WHEN 'KS' THEN 'Midwest'
        WHEN 'TX' THEN 'Southwest' WHEN 'OK' THEN 'Southwest' WHEN 'NM' THEN 'Southwest'
        WHEN 'AZ' THEN 'Southwest'
        WHEN 'CA' THEN 'West' WHEN 'OR' THEN 'West' WHEN 'WA' THEN 'West'
        WHEN 'NV' THEN 'West' WHEN 'ID' THEN 'West' WHEN 'MT' THEN 'West'
        WHEN 'WY' THEN 'West' WHEN 'CO' THEN 'West' WHEN 'UT' THEN 'West'
        WHEN 'AK' THEN 'West' WHEN 'HI' THEN 'West'
        ELSE 'Other'
    END,
    STATE_CODE IN ('FL','TX','CA','LA','AL','MS','SC','GA','NC','OK')
FROM u;

-- 12. DIM_PERIL
INSERT INTO PNC_DW.DIM_PERIL
    (PERIL_SK, PERIL_TYPE, PERIL_CATEGORY, IS_CATASTROPHE_PERIL)
WITH p AS (SELECT DISTINCT TRIM(PERIL_TYPE) AS PERIL_TYPE FROM PNC.LOSS_EVENT WHERE PERIL_TYPE IS NOT NULL)
SELECT
    PNC_DW.SEQ_PERIL_SK.NEXTVAL,
    PERIL_TYPE,
    CASE
        WHEN PERIL_TYPE ILIKE ANY ('%wind%','%hurricane%','%tornado%','%hail%','%flood%','%earthquake%','%storm%','%blizzard%','%ice%') THEN 'Weather'
        WHEN PERIL_TYPE ILIKE ANY ('%fire%','%smoke%','%lightning%') THEN 'Fire'
        WHEN PERIL_TYPE ILIKE ANY ('%theft%','%burglary%','%vandalism%','%robbery%') THEN 'Theft/Vandalism'
        WHEN PERIL_TYPE ILIKE ANY ('%liability%','%bodily injury%','%negligence%','%slip%') THEN 'Liability'
        WHEN PERIL_TYPE ILIKE ANY ('%collision%','%auto%','%vehicle%','%crash%') THEN 'Auto'
        ELSE 'Other'
    END,
    PERIL_TYPE ILIKE ANY ('%hurricane%','%tornado%','%earthquake%','%flood%','%wildfire%')
FROM p;

-- 13. DIM_BENEFICIARY
INSERT INTO PNC_DW.DIM_BENEFICIARY
    (BENEFICIARY_SK, BENEFICIARY_ID, POLICY_ID, FULL_NAME, EMAIL, PHONE,
     RELATIONSHIP, BENEFICIARY_TYPE, DOB, STATUS, DESIGNATION_DATE, MINOR_FLAG)
SELECT
    PNC_DW.SEQ_BENEFICIARY_SK.NEXTVAL,
    BENEFICIARY_ID, POLICY_ID,
    TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')),
    EMAIL, PHONE, RELATIONSHIP, BENEFICIARY_TYPE,
    TRY_TO_DATE(DOB::VARCHAR),
    STATUS,
    TRY_TO_DATE(DESIGNATION_DATE::VARCHAR),
    MINOR_FLAG::BOOLEAN
FROM PNC.BENEFICIARY;

-- 14. DIM_DOCUMENT_TYPE
INSERT INTO PNC_DW.DIM_DOCUMENT_TYPE
    (DOCUMENT_TYPE_SK, DOCUMENT_TYPE, DOCUMENT_CATEGORY)
SELECT
    PNC_DW.SEQ_DOC_TYPE_SK.NEXTVAL,
    DOCUMENT_TYPE,
    DOCUMENT_CATEGORY
FROM (
    SELECT DISTINCT DOCUMENT_TYPE, DOCUMENT_CATEGORY
    FROM PNC.DOCUMENT
    WHERE DOCUMENT_TYPE IS NOT NULL
) t;

-- 15. DIM_PAYMENT_METHOD
INSERT INTO PNC_DW.DIM_PAYMENT_METHOD
    (PAYMENT_METHOD_SK, PAYMENT_METHOD)
WITH m AS (
    SELECT DISTINCT TRIM(PAYMENT_METHOD) AS PAYMENT_METHOD FROM PNC.CLAIM_PAYMENT WHERE PAYMENT_METHOD IS NOT NULL
    UNION
    SELECT DISTINCT TRIM(PAYMENT_METHOD) FROM PNC.PREMIUM WHERE PAYMENT_METHOD IS NOT NULL
)
SELECT PNC_DW.SEQ_PAY_METHOD_SK.NEXTVAL, PAYMENT_METHOD FROM m;

-- 16. DIM_INVESTIGATION_TYPE
INSERT INTO PNC_DW.DIM_INVESTIGATION_TYPE
    (INVESTIGATION_TYPE_SK, INVESTIGATION_TYPE)
SELECT
    PNC_DW.SEQ_INV_TYPE_SK.NEXTVAL,
    INVESTIGATION_TYPE
FROM (SELECT DISTINCT TRIM(INVESTIGATION_TYPE) AS INVESTIGATION_TYPE FROM PNC.INVESTIGATION WHERE INVESTIGATION_TYPE IS NOT NULL) t;

-- 17. DIM_COMPLIANCE_REGULATION
INSERT INTO PNC_DW.DIM_COMPLIANCE_REGULATION
    (COMPLIANCE_REGULATION_SK, REGULATION, JURISDICTION)
SELECT
    PNC_DW.SEQ_COMP_REG_SK.NEXTVAL,
    REGULATION,
    JURISDICTION
FROM (SELECT DISTINCT TRIM(REGULATION) AS REGULATION, TRIM(JURISDICTION) AS JURISDICTION FROM PNC.COMPLIANCE WHERE REGULATION IS NOT NULL) t;

-- 18. DIM_CLAIM_TYPE
INSERT INTO PNC_DW.DIM_CLAIM_TYPE
    (CLAIM_TYPE_SK, CLAIM_TYPE, CLAIMANT_TYPE)
SELECT
    PNC_DW.SEQ_CLAIM_TYPE_SK.NEXTVAL,
    CLAIM_TYPE,
    CLAIMANT_TYPE
FROM (SELECT DISTINCT TRIM(CLAIM_TYPE) AS CLAIM_TYPE, TRIM(CLAIMANT_TYPE) AS CLAIMANT_TYPE FROM PNC.CLAIM WHERE CLAIM_TYPE IS NOT NULL) t;

-- 19. DIM_FRAUD_RISK_LEVEL
INSERT INTO PNC_DW.DIM_FRAUD_RISK_LEVEL
    (FRAUD_RISK_LEVEL_SK, FRAUD_RISK_LEVEL, PRIMARY_INDICATOR)
SELECT
    PNC_DW.SEQ_FRAUD_LEVEL_SK.NEXTVAL,
    FRAUD_RISK_LEVEL,
    PRIMARY_INDICATOR
FROM (SELECT DISTINCT TRIM(FRAUD_RISK_LEVEL) AS FRAUD_RISK_LEVEL, TRIM(PRIMARY_INDICATOR) AS PRIMARY_INDICATOR FROM PNC.FRAUD_INDICATOR WHERE FRAUD_RISK_LEVEL IS NOT NULL) t;

-- 20. DIM_DISTRIBUTION_CHANNEL
INSERT INTO PNC_DW.DIM_DISTRIBUTION_CHANNEL
    (DISTRIBUTION_CHANNEL_SK, DISTRIBUTION_CHANNEL, POLICY_TIER)
SELECT
    PNC_DW.SEQ_DIST_CHAN_SK.NEXTVAL,
    DISTRIBUTION_CHANNEL,
    POLICY_TIER
FROM (SELECT DISTINCT TRIM(DISTRIBUTION_CHANNEL) AS DISTRIBUTION_CHANNEL, TRIM(POLICY_TIER) AS POLICY_TIER FROM PNC.POLICY WHERE DISTRIBUTION_CHANNEL IS NOT NULL) t;

-- 21. DIM_POLICY_TYPE
INSERT INTO PNC_DW.DIM_POLICY_TYPE
    (POLICY_TYPE_SK, POLICY_TYPE, BUSINESS_TYPE)
SELECT
    PNC_DW.SEQ_POLICY_TYPE_SK.NEXTVAL,
    POLICY_TYPE,
    BUSINESS_TYPE
FROM (SELECT DISTINCT TRIM(POLICY_TYPE) AS POLICY_TYPE, TRIM(BUSINESS_TYPE) AS BUSINESS_TYPE FROM PNC.POLICY WHERE POLICY_TYPE IS NOT NULL) t;

-- 22. DIM_AUDIT_ACTION
INSERT INTO PNC_DW.DIM_AUDIT_ACTION
    (AUDIT_ACTION_SK, ACTION, OPERATION_TYPE, USER_ROLE)
SELECT
    PNC_DW.SEQ_AUDIT_ACTION_SK.NEXTVAL,
    ACTION,
    OPERATION_TYPE,
    USER_ROLE
FROM (SELECT DISTINCT TRIM(ACTION) AS ACTION, TRIM(OPERATION_TYPE) AS OPERATION_TYPE, TRIM(USER_ROLE) AS USER_ROLE FROM PNC.AUDIT_LOG WHERE ACTION IS NOT NULL) t;

-- 23. DIM_COVERAGE_STATUS
INSERT INTO PNC_DW.DIM_COVERAGE_STATUS
    (COVERAGE_STATUS_SK, COVERAGE_STATUS, VALUATION_METHOD, ENDORSEMENT_STATUS)
SELECT
    PNC_DW.SEQ_COV_STATUS_SK.NEXTVAL,
    COVERAGE_STATUS,
    VALUATION_METHOD,
    ENDORSEMENT_STATUS
FROM (SELECT DISTINCT TRIM(COVERAGE_STATUS) AS COVERAGE_STATUS, TRIM(VALUATION_METHOD) AS VALUATION_METHOD, TRIM(ENDORSEMENT_STATUS) AS ENDORSEMENT_STATUS FROM PNC.COVERAGE WHERE COVERAGE_STATUS IS NOT NULL) t;

-- =============================================================================
-- LOAD FACTS
-- =============================================================================

-- 1. FACT_CLAIMS
INSERT INTO PNC_DW.FACT_CLAIMS
    (CLAIM_SK, CLAIM_ID,
     POLICY_SK, POLICYHOLDER_SK, ADJUSTER_SK, AGENT_SK,
     CLAIM_TYPE_SK, FRAUD_RISK_LEVEL_SK,
     DATE_FILED_SK, DATE_CLOSED_SK,
     CLAIM_STATUS, SEVERITY, REPORTING_METHOD,
     LITIGATION_FLAG, SUBROGATION_FLAG,
     HAS_FRAUD_INDICATOR, FRAUD_SCORE,
     CLAIMED_AMOUNT, APPROVED_AMOUNT, DEDUCTIBLE_APPLIED,
     NET_APPROVED_AMOUNT, TOTAL_PAID_AMOUNT, CLAIM_RECOVERY_PCT, DAYS_TO_CLOSE)
WITH paid AS (
    SELECT CLAIM_ID, SUM(PAYMENT_AMOUNT) AS TOTAL_PAID FROM PNC.CLAIM_PAYMENT GROUP BY CLAIM_ID
),
fraud AS (
    SELECT CLAIM_ID, FRAUD_SCORE, FRAUD_RISK_LEVEL, PRIMARY_INDICATOR,
           ROW_NUMBER() OVER (PARTITION BY CLAIM_ID ORDER BY DETECTION_DATE DESC) AS rn
    FROM PNC.FRAUD_INDICATOR
)
SELECT
    PNC_DW.SEQ_FACT_CLAIMS_SK.NEXTVAL,
    c.CLAIM_ID,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    da.ADJUSTER_SK,
    dp.AGENT_SK,
    dct.CLAIM_TYPE_SK,
    dfr.FRAUD_RISK_LEVEL_SK,
    ddf.DATE_SK,
    ddc.DATE_SK,
    c.CLAIM_STATUS,
    c.SEVERITY,
    c.REPORTING_METHOD,
    TRY_CAST(c.LITIGATION_FLAG  AS BOOLEAN),
    TRY_CAST(c.SUBROGATION_FLAG AS BOOLEAN),
    (f.CLAIM_ID IS NOT NULL),
    f.FRAUD_SCORE,
    c.CLAIMED_AMOUNT,
    c.APPROVED_AMOUNT,
    c.DEDUCTIBLE_APPLIED,
    NVL(c.APPROVED_AMOUNT,0) - NVL(c.DEDUCTIBLE_APPLIED,0),
    NVL(p2.TOTAL_PAID,0),
    IFF(c.CLAIMED_AMOUNT > 0, c.APPROVED_AMOUNT / c.CLAIMED_AMOUNT, NULL),
    DATEDIFF(DAY, TRY_TO_DATE(c.DATE_FILED::VARCHAR), TRY_TO_DATE(c.DATE_CLOSED::VARCHAR))
FROM PNC.CLAIM c
LEFT JOIN PNC_DW.DIM_POLICY           dp  ON dp.POLICY_ID    = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_ADJUSTER         da  ON da.ADJUSTER_ID  = c.ADJUSTER_ID
LEFT JOIN PNC_DW.DIM_CLAIM_TYPE       dct ON dct.CLAIM_TYPE  = TRIM(c.CLAIM_TYPE)
                                         AND dct.CLAIMANT_TYPE = TRIM(c.CLAIMANT_TYPE)
LEFT JOIN fraud                        f   ON f.CLAIM_ID      = c.CLAIM_ID AND f.rn = 1
LEFT JOIN PNC_DW.DIM_FRAUD_RISK_LEVEL dfr ON dfr.FRAUD_RISK_LEVEL = TRIM(f.FRAUD_RISK_LEVEL)
                                         AND dfr.PRIMARY_INDICATOR  = TRIM(f.PRIMARY_INDICATOR)
LEFT JOIN PNC_DW.DIM_DATE             ddf ON ddf.FULL_DATE    = TRY_TO_DATE(c.DATE_FILED::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE             ddc ON ddc.FULL_DATE    = TRY_TO_DATE(c.DATE_CLOSED::VARCHAR)
LEFT JOIN paid                         p2  ON p2.CLAIM_ID     = c.CLAIM_ID;

-- 2. FACT_PREMIUMS
INSERT INTO PNC_DW.FACT_PREMIUMS
    (PREMIUM_SK, PREMIUM_ID,
     POLICY_SK, POLICYHOLDER_SK, AGENT_SK, PAYMENT_METHOD_SK,
     PREMIUM_START_DATE_SK, PREMIUM_END_DATE_SK, LAST_PAYMENT_DATE_SK,
     PAYMENT_SCHEDULE, PAYMENT_STATUS, AUTOPAY_ENROLLED,
     BASE_PREMIUM, DISCOUNT_AMOUNT, SURCHARGE_AMOUNT, FINAL_PREMIUM,
     LATE_FEE, INSTALLMENT_FEE, TOTAL_BILLED, NET_DISCOUNT_RATE)
SELECT
    PNC_DW.SEQ_FACT_PREMIUMS_SK.NEXTVAL,
    pr.PREMIUM_ID,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    dp.AGENT_SK,
    dpm.PAYMENT_METHOD_SK,
    ds.DATE_SK,
    de.DATE_SK,
    dlp.DATE_SK,
    pr.PAYMENT_SCHEDULE,
    pr.PAYMENT_STATUS,
    pr.AUTOPAY_ENROLLED::BOOLEAN,
    pr.BASE_PREMIUM,
    NVL(pr.DISCOUNT_AMOUNT,0),
    NVL(pr.SURCHARGE_AMOUNT,0),
    pr.FINAL_PREMIUM,
    NVL(pr.LATE_FEE,0),
    NVL(pr.INSTALLMENT_FEE,0),
    NVL(pr.FINAL_PREMIUM,0) + NVL(pr.LATE_FEE,0) + NVL(pr.INSTALLMENT_FEE,0),
    IFF(pr.BASE_PREMIUM > 0, NVL(pr.DISCOUNT_AMOUNT,0) / pr.BASE_PREMIUM, NULL)
FROM PNC.PREMIUM pr
LEFT JOIN PNC_DW.DIM_POLICY         dp  ON dp.POLICY_ID      = pr.POLICY_ID
LEFT JOIN PNC_DW.DIM_PAYMENT_METHOD dpm ON dpm.PAYMENT_METHOD = TRIM(pr.PAYMENT_METHOD)
LEFT JOIN PNC_DW.DIM_DATE           ds  ON ds.FULL_DATE       = TRY_TO_DATE(pr.PREMIUM_START_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE           de  ON de.FULL_DATE       = TRY_TO_DATE(pr.PREMIUM_END_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE           dlp ON dlp.FULL_DATE      = TRY_TO_DATE(pr.LAST_PAYMENT_DATE::VARCHAR);

-- 3. FACT_CLAIM_PAYMENTS
INSERT INTO PNC_DW.FACT_CLAIM_PAYMENTS
    (PAYMENT_SK, PAYMENT_ID, CLAIM_ID,
     POLICY_SK, POLICYHOLDER_SK, PAYMENT_METHOD_SK, PAYMENT_DATE_SK,
     PAYMENT_TYPE, PAYMENT_STATUS, PAYEE_TYPE, CURRENCY,
     TAX_WITHHELD_FLAG, ISSUED_1099_FLAG, REFERENCE_NUMBER,
     PAYMENT_AMOUNT, WITHHOLDING_AMOUNT, NET_PAYMENT)
SELECT
    PNC_DW.SEQ_FACT_PAYMENTS_SK.NEXTVAL,
    cp.PAYMENT_ID,
    cp.CLAIM_ID,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    dpm.PAYMENT_METHOD_SK,
    dd.DATE_SK,
    cp.PAYMENT_TYPE,
    cp.PAYMENT_STATUS,
    cp.PAYEE_TYPE,
    cp.CURRENCY,
    cp.TAX_WITHHELD_FLAG::BOOLEAN,
    cp.ISSUED_1099_FLAG::BOOLEAN,
    cp.REFERENCE_NUMBER,
    cp.PAYMENT_AMOUNT,
    NVL(cp.WITHHOLDING_AMOUNT,0),
    NVL(cp.PAYMENT_AMOUNT,0) - NVL(cp.WITHHOLDING_AMOUNT,0)
FROM PNC.CLAIM_PAYMENT cp
LEFT JOIN PNC.CLAIM c               ON c.CLAIM_ID       = cp.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY         dp  ON dp.POLICY_ID = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_PAYMENT_METHOD dpm ON dpm.PAYMENT_METHOD = TRIM(cp.PAYMENT_METHOD)
LEFT JOIN PNC_DW.DIM_DATE           dd  ON dd.FULL_DATE  = TRY_TO_DATE(cp.PAYMENT_DATE::VARCHAR);

-- 4. FACT_CLAIM_ASSESSMENT
INSERT INTO PNC_DW.FACT_CLAIM_ASSESSMENT
    (ASSESSMENT_SK, ASSESSMENT_ID, CLAIM_ID,
     POLICY_SK, ADJUSTER_SK, ASSESSMENT_DATE_SK,
     ASSESSMENT_METHOD, RECOMMENDATION, EVIDENCE_STRENGTH,
     COMPLEXITY_LEVEL, DOCUMENTATION_STATUS, EXPERT_CONSULTED,
     ESTIMATED_LOSS, RECOMMENDED_PAYOUT, SALVAGE_VALUE,
     HOURS_SPENT, REVISION_COUNT, ASSESSMENT_ACCURACY_PCT)
SELECT
    PNC_DW.SEQ_FACT_ASSESS_SK.NEXTVAL,
    ca.ASSESSMENT_ID,
    ca.CLAIM_ID,
    dp.POLICY_SK,
    da.ADJUSTER_SK,
    dd.DATE_SK,
    ca.ASSESSMENT_METHOD,
    ca.RECOMMENDATION,
    ca.EVIDENCE_STRENGTH,
    ca.COMPLEXITY_LEVEL,
    ca.DOCUMENTATION_STATUS,
    ca.EXPERT_CONSULTED::BOOLEAN,
    ca.ESTIMATED_LOSS,
    ca.RECOMMENDED_PAYOUT,
    NVL(ca.SALVAGE_VALUE,0),
    ca.HOURS_SPENT,
    ca.REVISION_COUNT,
    IFF(ca.ESTIMATED_LOSS > 0, ca.RECOMMENDED_PAYOUT / ca.ESTIMATED_LOSS, NULL)
FROM PNC.CLAIM_ASSESSMENT ca
LEFT JOIN PNC.CLAIM c            ON c.CLAIM_ID     = ca.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY   dp ON dp.POLICY_ID   = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_ADJUSTER da ON da.ADJUSTER_ID = ca.ADJUSTER_ID
LEFT JOIN PNC_DW.DIM_DATE     dd ON dd.FULL_DATE    = TRY_TO_DATE(ca.ASSESSMENT_DATE::VARCHAR);

-- 5. FACT_RISK_UNDERWRITING
INSERT INTO PNC_DW.FACT_RISK_UNDERWRITING
    (RISK_SK, RISK_PROFILE_ID,
     POLICY_SK, POLICYHOLDER_SK, UNDERWRITER_SK, ASSESSMENT_DATE_SK,
     RISK_CATEGORY, UNDERWRITING_DECISION, RATE_CLASS,
     PRIOR_CLAIMS_FLAG, HIGH_VALUE_FLAG, CATASTROPHE_EXPOSURE, REVIEW_FREQUENCY,
     RISK_SCORE, LOSS_PROBABILITY, RATE_MODIFIER, EXPECTED_LOSS_AMOUNT)
SELECT
    PNC_DW.SEQ_FACT_RISK_SK.NEXTVAL,
    rp.RISK_PROFILE_ID,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    du.UNDERWRITER_SK,
    dd.DATE_SK,
    rp.RISK_CATEGORY,
    rp.UNDERWRITING_DECISION,
    rp.RATE_CLASS,
    rp.PRIOR_CLAIMS_FLAG::BOOLEAN,
    rp.HIGH_VALUE_FLAG::BOOLEAN,
    rp.CATASTROPHE_EXPOSURE,
    rp.REVIEW_FREQUENCY,
    rp.RISK_SCORE,
    rp.LOSS_PROBABILITY,
    rp.RATE_MODIFIER,
    rp.EXPECTED_LOSS_AMOUNT
FROM PNC.RISK_PROFILE rp
LEFT JOIN PNC_DW.DIM_POLICY       dp ON dp.POLICY_ID      = rp.POLICY_ID
LEFT JOIN PNC_DW.DIM_UNDERWRITER  du ON du.UNDERWRITER_ID = rp.UNDERWRITER_ID
LEFT JOIN PNC_DW.DIM_DATE         dd ON dd.FULL_DATE       = TRY_TO_DATE(rp.ASSESSMENT_DATE::VARCHAR);

-- 6. FACT_FRAUD_DETECTION
INSERT INTO PNC_DW.FACT_FRAUD_DETECTION
    (FRAUD_SK, FRAUD_INDICATOR_ID, CLAIM_ID,
     POLICY_SK, FRAUD_RISK_LEVEL_SK, DETECTION_DATE_SK,
     DETECTION_METHOD, INVESTIGATION_STATUS,
     LAW_ENFORCEMENT_NOTIFIED, PROSECUTION_FLAG, SIU_ASSIGNED,
     FRAUD_SCORE, ESTIMATED_FRAUD_AMOUNT)
SELECT
    PNC_DW.SEQ_FACT_FRAUD_SK.NEXTVAL,
    fi.FRAUD_INDICATOR_ID,
    fi.CLAIM_ID,
    dp.POLICY_SK,
    dfr.FRAUD_RISK_LEVEL_SK,
    dd.DATE_SK,
    fi.DETECTION_METHOD,
    fi.INVESTIGATION_STATUS,
    fi.LAW_ENFORCEMENT_NOTIFIED::BOOLEAN,
    fi.PROSECUTION_FLAG::BOOLEAN,
    TRY_CAST(fi.SIU_ASSIGNED AS BOOLEAN),
    fi.FRAUD_SCORE,
    NVL(fi.ESTIMATED_FRAUD_AMOUNT,0)
FROM PNC.FRAUD_INDICATOR fi
LEFT JOIN PNC.CLAIM c                  ON c.CLAIM_ID        = fi.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY         dp  ON dp.POLICY_ID     = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_FRAUD_RISK_LEVEL dfr ON dfr.FRAUD_RISK_LEVEL = TRIM(fi.FRAUD_RISK_LEVEL)
                                         AND dfr.PRIMARY_INDICATOR  = TRIM(fi.PRIMARY_INDICATOR)
LEFT JOIN PNC_DW.DIM_DATE           dd  ON dd.FULL_DATE      = TRY_TO_DATE(fi.DETECTION_DATE::VARCHAR);

-- 7. FACT_INVESTIGATION
INSERT INTO PNC_DW.FACT_INVESTIGATION
    (INVESTIGATION_SK, INVESTIGATION_ID, CLAIM_ID,
     POLICY_SK, INVESTIGATION_TYPE_SK,
     START_DATE_SK, END_DATE_SK,
     STATUS, LEAD_INVESTIGATOR, OUTCOME,
     SURVEILLANCE_CONDUCTED, LEGAL_HOLD, COURT_SUBPOENA, PRIORITY,
     INVESTIGATION_COST, DURATION_DAYS)
SELECT
    PNC_DW.SEQ_FACT_INV_SK.NEXTVAL,
    i.INVESTIGATION_ID,
    i.CLAIM_ID,
    dp.POLICY_SK,
    dit.INVESTIGATION_TYPE_SK,
    ds.DATE_SK,
    de.DATE_SK,
    i.STATUS,
    i.LEAD_INVESTIGATOR,
    i.OUTCOME,
    i.SURVEILLANCE_CONDUCTED::BOOLEAN,
    i.LEGAL_HOLD::BOOLEAN,
    i.COURT_SUBPOENA::BOOLEAN,
    i.PRIORITY,
    NVL(i.INVESTIGATION_COST,0),
    i.DURATION_DAYS
FROM PNC.INVESTIGATION i
LEFT JOIN PNC.CLAIM c                      ON c.CLAIM_ID         = i.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY            dp  ON dp.POLICY_ID       = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_INVESTIGATION_TYPE dit ON dit.INVESTIGATION_TYPE = TRIM(i.INVESTIGATION_TYPE)
LEFT JOIN PNC_DW.DIM_DATE              ds  ON ds.FULL_DATE        = TRY_TO_DATE(i.START_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE              de  ON de.FULL_DATE        = TRY_TO_DATE(i.END_DATE::VARCHAR);

-- 8. FACT_DEDUCTIBLE_TRACKING
INSERT INTO PNC_DW.FACT_DEDUCTIBLE_TRACKING
    (DEDUCTIBLE_SK, DEDUCTIBLE_ID, CLAIM_ID,
     COVERAGE_SK, POLICY_SK, APPLIED_DATE_SK,
     STATUS, DEDUCTIBLE_TYPE, DEDUCTIBLE_STRUCTURE, WAIVER_APPROVED,
     SCHEDULED_DEDUCTIBLE, APPLIED_AMOUNT, WAIVED_AMOUNT, NET_DEDUCTIBLE)
SELECT
    PNC_DW.SEQ_FACT_DED_SK.NEXTVAL,
    dt.DEDUCTIBLE_ID,
    dt.CLAIM_ID,
    dc.COVERAGE_SK,
    dp.POLICY_SK,
    dd.DATE_SK,
    dt.STATUS,
    dt.DEDUCTIBLE_TYPE,
    dt.DEDUCTIBLE_STRUCTURE,
    dt.WAIVER_APPROVED::BOOLEAN,
    NVL(dt.SCHEDULED_DEDUCTIBLE,0),
    NVL(dt.APPLIED_AMOUNT,0),
    NVL(dt.WAIVED_AMOUNT,0),
    NVL(dt.NET_DEDUCTIBLE,0)
FROM PNC.DEDUCTIBLE_TRACKING dt
LEFT JOIN PNC_DW.DIM_COVERAGE dc ON dc.COVERAGE_ID = dt.COVERAGE_ID
LEFT JOIN PNC.CLAIM c             ON c.CLAIM_ID     = dt.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY  dp   ON dp.POLICY_ID   = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_DATE    dd   ON dd.FULL_DATE    = TRY_TO_DATE(dt.APPLIED_DATE::VARCHAR);

-- 9. FACT_COMPLIANCE
INSERT INTO PNC_DW.FACT_COMPLIANCE
    (COMPLIANCE_SK, COMPLIANCE_ID,
     POLICY_SK, COMPLIANCE_REGULATION_SK,
     EFFECTIVE_DATE_SK, EXPIRY_DATE_SK, LAST_REVIEW_DATE_SK,
     COMPLIANCE_STATUS, RISK_LEVEL, AUDIT_RESULT, REVIEW_TYPE,
     REMEDIATION_STATUS, REPORTED_TO_REGULATOR, PENALTY_AMOUNT)
SELECT
    PNC_DW.SEQ_FACT_COMP_SK.NEXTVAL,
    co.COMPLIANCE_ID,
    dp.POLICY_SK,
    dcr.COMPLIANCE_REGULATION_SK,
    de.DATE_SK,
    dx.DATE_SK,
    dlr.DATE_SK,
    co.COMPLIANCE_STATUS,
    co.RISK_LEVEL,
    co.AUDIT_RESULT,
    co.REVIEW_TYPE,
    co.REMEDIATION_STATUS,
    co.REPORTED_TO_REGULATOR::BOOLEAN,
    NVL(co.PENALTY_AMOUNT,0)
FROM PNC.COMPLIANCE co
LEFT JOIN PNC_DW.DIM_POLICY                 dp  ON dp.POLICY_ID  = co.POLICY_ID
LEFT JOIN PNC_DW.DIM_COMPLIANCE_REGULATION  dcr ON dcr.REGULATION  = TRIM(co.REGULATION)
                                               AND dcr.JURISDICTION = TRIM(co.JURISDICTION)
LEFT JOIN PNC_DW.DIM_DATE de  ON de.FULL_DATE  = TRY_TO_DATE(co.EFFECTIVE_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE dx  ON dx.FULL_DATE  = TRY_TO_DATE(co.EXPIRY_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE dlr ON dlr.FULL_DATE = TRY_TO_DATE(co.LAST_REVIEW_DATE::VARCHAR);

-- 10. FACT_REINSURANCE
INSERT INTO PNC_DW.FACT_REINSURANCE
    (REINSURANCE_SK, REINSURANCE_ID,
     POLICY_SK, REINSURER_SK,
     TREATY_START_SK, TREATY_END_SK,
     TREATY_TYPE, TREATY_STATUS, CLAIMS_CEDED_FLAG,
     CESSION_PERCENTAGE, CEDED_LIMIT, RETAINED_LIMIT,
     REINSURANCE_PREMIUM, COMMISSION_RATE)
SELECT
    PNC_DW.SEQ_FACT_REIN_SK.NEXTVAL,
    r.REINSURANCE_ID,
    dp.POLICY_SK,
    dr.REINSURER_SK,
    ds.DATE_SK,
    de.DATE_SK,
    r.TREATY_TYPE,
    r.TREATY_STATUS,
    r.CLAIMS_CEDED_FLAG::BOOLEAN,
    NVL(r.CESSION_PERCENTAGE,0),
    NVL(r.CEDED_LIMIT,0),
    NVL(r.RETAINED_LIMIT,0),
    NVL(r.REINSURANCE_PREMIUM,0),
    NVL(r.COMMISSION_RATE,0)
FROM PNC.REINSURANCE r
LEFT JOIN PNC_DW.DIM_POLICY     dp ON dp.POLICY_ID      = r.POLICY_ID
LEFT JOIN PNC_DW.DIM_REINSURER  dr ON dr.REINSURER_NAME = r.REINSURER_NAME
LEFT JOIN PNC_DW.DIM_DATE       ds ON ds.FULL_DATE       = TRY_TO_DATE(r.TREATY_START::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE       de ON de.FULL_DATE       = TRY_TO_DATE(r.TREATY_END::VARCHAR);

-- 11. FACT_LOSS_EVENT
INSERT INTO PNC_DW.FACT_LOSS_EVENT
    (LOSS_EVENT_SK, EVENT_ID, CLAIM_ID,
     POLICY_SK, PERIL_SK, GEOGRAPHY_SK, EVENT_DATE_SK,
     PROPERTY_TYPE, SEVERITY_LEVEL, EVENT_STATUS,
     CAT_EVENT_FLAG, CAT_EVENT_CODE, RESPONSIBLE_PARTY,
     ESTIMATED_DAMAGE, DURATION_DAYS, PROPERTIES_AFFECTED, TOTAL_INDUSTRY_LOSS_EST)
SELECT
    PNC_DW.SEQ_FACT_LOSS_SK.NEXTVAL,
    le.EVENT_ID,
    le.CLAIM_ID,
    dp.POLICY_SK,
    dpe.PERIL_SK,
    dg.GEOGRAPHY_SK,
    dd.DATE_SK,
    le.PROPERTY_TYPE,
    le.SEVERITY_LEVEL,
    le.EVENT_STATUS,
    le.CAT_EVENT_FLAG::BOOLEAN,
    le.CAT_EVENT_CODE,
    le.RESPONSIBLE_PARTY,
    NVL(le.ESTIMATED_DAMAGE,0),
    le.DURATION_DAYS,
    NVL(le.PROPERTIES_AFFECTED,0),
    NVL(le.TOTAL_INDUSTRY_LOSS_EST,0)
FROM PNC.LOSS_EVENT le
LEFT JOIN PNC.CLAIM c             ON c.CLAIM_ID      = le.CLAIM_ID
LEFT JOIN PNC_DW.DIM_POLICY dp    ON dp.POLICY_ID    = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_PERIL  dpe   ON dpe.PERIL_TYPE  = TRIM(le.PERIL_TYPE)
LEFT JOIN PNC_DW.DIM_GEOGRAPHY dg ON dg.STATE_CODE   = UPPER(TRIM(le.STATE))
LEFT JOIN PNC_DW.DIM_DATE  dd     ON dd.FULL_DATE     = TRY_TO_DATE(le.EVENT_DATE::VARCHAR);

-- 12. FACT_DOCUMENT_ACTIVITY
INSERT INTO PNC_DW.FACT_DOCUMENT_ACTIVITY
    (DOCUMENT_SK, DOCUMENT_ID, REFERENCE_ID, REFERENCE_TYPE,
     DOCUMENT_TYPE_SK, UPLOAD_DATE_SK,
     DOCUMENT_STATUS, FILE_FORMAT, STORAGE_PATH,
     VERIFIED, CONFIDENTIAL, FILE_SIZE_MB)
SELECT
    PNC_DW.SEQ_FACT_DOC_SK.NEXTVAL,
    d.DOCUMENT_ID,
    d.REFERENCE_ID,
    d.REFERENCE_TYPE,
    ddt.DOCUMENT_TYPE_SK,
    dd.DATE_SK,
    d.DOCUMENT_STATUS,
    d.FILE_FORMAT,
    d.STORAGE_PATH,
    d.VERIFIED::BOOLEAN,
    d.CONFIDENTIAL::BOOLEAN,
    NVL(d.FILE_SIZE_MB,0)
FROM PNC.DOCUMENT d
LEFT JOIN PNC_DW.DIM_DOCUMENT_TYPE ddt ON ddt.DOCUMENT_TYPE     = TRIM(d.DOCUMENT_TYPE)
                                      AND ddt.DOCUMENT_CATEGORY  = TRIM(d.DOCUMENT_CATEGORY)
LEFT JOIN PNC_DW.DIM_DATE          dd  ON dd.FULL_DATE           = TRY_TO_DATE(d.UPLOAD_DATE::VARCHAR);

-- 13. FACT_AUDIT_LOG
INSERT INTO PNC_DW.FACT_AUDIT_LOG
    (AUDIT_SK, AUDIT_ID, AUDIT_ACTION_SK, EVENT_DATE_SK,
     TABLE_NAME, RECORD_ID, USER_ID, IP_ADDRESS,
     ACTION_STATUS, REGULATORY_EVENT, CHANGE_DESCRIPTION, EVENT_COUNT)
SELECT
    PNC_DW.SEQ_FACT_AUDIT_SK.NEXTVAL,
    al.AUDIT_ID,
    daa.AUDIT_ACTION_SK,
    dd.DATE_SK,
    al.TABLE_NAME,
    al.RECORD_ID,
    al.USER_ID,
    al.IP_ADDRESS,
    al.ACTION_STATUS,
    al.REGULATORY_EVENT,
    al.CHANGE_DESCRIPTION,
    1
FROM PNC.AUDIT_LOG al
LEFT JOIN PNC_DW.DIM_AUDIT_ACTION daa ON daa.ACTION         = TRIM(al.ACTION)
                                     AND daa.OPERATION_TYPE  = TRIM(al.OPERATION_TYPE)
                                     AND daa.USER_ROLE        = TRIM(al.USER_ROLE)
LEFT JOIN PNC_DW.DIM_DATE         dd  ON dd.FULL_DATE        = TRY_TO_DATE(al.TIMESTAMP::VARCHAR);

-- 14. FACT_BENEFICIARY
INSERT INTO PNC_DW.FACT_BENEFICIARY
    (BENEFICIARY_FACT_SK, BENEFICIARY_SK, POLICY_SK,
     DESIGNATION_DATE_SK, STATUS, MINOR_FLAG, BENEFIT_PERCENTAGE)
SELECT
    PNC_DW.SEQ_FACT_BENEF_SK.NEXTVAL,
    db.BENEFICIARY_SK,
    dp.POLICY_SK,
    dd.DATE_SK,
    b.STATUS,
    b.MINOR_FLAG::BOOLEAN,
    NVL(b.BENEFIT_PERCENTAGE,0)
FROM PNC.BENEFICIARY b
LEFT JOIN PNC_DW.DIM_BENEFICIARY db ON db.BENEFICIARY_ID = b.BENEFICIARY_ID
LEFT JOIN PNC_DW.DIM_POLICY      dp ON dp.POLICY_ID      = b.POLICY_ID
LEFT JOIN PNC_DW.DIM_DATE        dd ON dd.FULL_DATE       = TRY_TO_DATE(b.DESIGNATION_DATE::VARCHAR);

-- 15. FACT_COVERAGE_UTILIZATION
INSERT INTO PNC_DW.FACT_COVERAGE_UTILIZATION
    (COVERAGE_UTIL_SK, COVERAGE_SK, POLICY_SK, COVERAGE_STATUS_SK, EFFECTIVE_DATE_SK,
     COVERAGE_LIMIT, SUB_LIMIT, DEDUCTIBLE_AMOUNT,
     APPLIED_DEDUCTIBLE_TOTAL, WAIVED_DEDUCTIBLE_TOTAL, UTILIZATION_PCT)
WITH ded_agg AS (
    SELECT COVERAGE_ID,
           SUM(APPLIED_AMOUNT) AS APPLIED_TOTAL,
           SUM(WAIVED_AMOUNT)  AS WAIVED_TOTAL
    FROM PNC.DEDUCTIBLE_TRACKING
    GROUP BY COVERAGE_ID
)
SELECT
    PNC_DW.SEQ_FACT_COV_UTIL_SK.NEXTVAL,
    dc.COVERAGE_SK,
    dp.POLICY_SK,
    dcs.COVERAGE_STATUS_SK,
    dd.DATE_SK,
    NVL(c.COVERAGE_LIMIT,0),
    NVL(c.SUB_LIMIT,0),
    NVL(c.DEDUCTIBLE_AMOUNT,0),
    NVL(da.APPLIED_TOTAL,0),
    NVL(da.WAIVED_TOTAL,0),
    IFF(c.COVERAGE_LIMIT > 0, NVL(da.APPLIED_TOTAL,0) / c.COVERAGE_LIMIT, NULL)
FROM PNC.COVERAGE c
LEFT JOIN PNC_DW.DIM_COVERAGE     dc  ON dc.COVERAGE_ID    = c.COVERAGE_ID
LEFT JOIN PNC_DW.DIM_POLICY       dp  ON dp.POLICY_ID      = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_COVERAGE_STATUS dcs ON dcs.COVERAGE_STATUS   = TRIM(c.COVERAGE_STATUS)
                                        AND dcs.VALUATION_METHOD   = TRIM(c.VALUATION_METHOD)
                                        AND dcs.ENDORSEMENT_STATUS = TRIM(c.ENDORSEMENT_STATUS)
LEFT JOIN PNC_DW.DIM_DATE         dd  ON dd.FULL_DATE       = TRY_TO_DATE(c.EFFECTIVE_DATE::VARCHAR)
LEFT JOIN ded_agg                 da  ON da.COVERAGE_ID     = c.COVERAGE_ID;

-- 16. FACT_ADJUSTER_MONTHLY_SNAPSHOT
INSERT INTO PNC_DW.FACT_ADJUSTER_MONTHLY_SNAPSHOT
    (ADJUSTER_MONTHLY_SK, ADJUSTER_SK, SNAPSHOT_YEAR, SNAPSHOT_MONTH,
     CLAIMS_HANDLED, AVG_DAYS_TO_CLOSE, TOTAL_APPROVED,
     ASSESSMENTS_DONE, TOTAL_HOURS_SPENT, AVG_REVISION_COUNT, LITIGATION_COUNT)
WITH claim_agg AS (
    SELECT
        c.ADJUSTER_ID,
        YEAR(TRY_TO_DATE(c.DATE_FILED::VARCHAR))  AS YR,
        MONTH(TRY_TO_DATE(c.DATE_FILED::VARCHAR)) AS MO,
        COUNT(*)                                  AS CLAIMS_HANDLED,
        AVG(DATEDIFF(DAY, TRY_TO_DATE(c.DATE_FILED::VARCHAR), TRY_TO_DATE(c.DATE_CLOSED::VARCHAR))) AS AVG_DTC,
        SUM(c.APPROVED_AMOUNT)                    AS TOTAL_APPROVED,
        SUM(CASE WHEN c.LITIGATION_FLAG::BOOLEAN THEN 1 ELSE 0 END) AS LIT_COUNT
    FROM PNC.CLAIM c
    WHERE TRY_TO_DATE(c.DATE_FILED::VARCHAR) IS NOT NULL
    GROUP BY 1,2,3
),
assess_agg AS (
    SELECT
        ca.ADJUSTER_ID,
        YEAR(TRY_TO_DATE(ca.ASSESSMENT_DATE::VARCHAR))  AS YR,
        MONTH(TRY_TO_DATE(ca.ASSESSMENT_DATE::VARCHAR)) AS MO,
        COUNT(*)          AS ASSESSMENTS_DONE,
        SUM(ca.HOURS_SPENT) AS TOTAL_HOURS,
        AVG(ca.REVISION_COUNT) AS AVG_REV
    FROM PNC.CLAIM_ASSESSMENT ca
    WHERE TRY_TO_DATE(ca.ASSESSMENT_DATE::VARCHAR) IS NOT NULL
    GROUP BY 1,2,3
)
SELECT
    PNC_DW.SEQ_FACT_ADJ_MON_SK.NEXTVAL,
    da.ADJUSTER_SK,
    COALESCE(cl.YR, aa.YR)             AS SNAPSHOT_YEAR,
    COALESCE(cl.MO, aa.MO)             AS SNAPSHOT_MONTH,
    NVL(cl.CLAIMS_HANDLED,0),
    cl.AVG_DTC,
    NVL(cl.TOTAL_APPROVED,0),
    NVL(aa.ASSESSMENTS_DONE,0),
    NVL(aa.TOTAL_HOURS,0),
    aa.AVG_REV,
    NVL(cl.LIT_COUNT,0)
FROM PNC_DW.DIM_ADJUSTER da
LEFT JOIN claim_agg  cl ON cl.ADJUSTER_ID = da.ADJUSTER_ID
LEFT JOIN assess_agg aa ON aa.ADJUSTER_ID = da.ADJUSTER_ID
                        AND aa.YR = cl.YR AND aa.MO = cl.MO
WHERE COALESCE(cl.YR, aa.YR) IS NOT NULL;

-- 17. FACT_AGENT_PERFORMANCE_MONTHLY
INSERT INTO PNC_DW.FACT_AGENT_PERFORMANCE_MONTHLY
    (AGENT_MONTHLY_SK, AGENT_SK, SNAPSHOT_YEAR, SNAPSHOT_MONTH,
     POLICIES_WRITTEN, NEW_POLICIES, TOTAL_PREMIUM_COLLECTED,
     AVG_DISCOUNT_RATE, TOTAL_DISCOUNTS_GIVEN, TOTAL_LATE_FEES)
WITH prem_agg AS (
    SELECT
        po.AGENT_ID,
        YEAR(TRY_TO_DATE(pr.PREMIUM_START_DATE::VARCHAR))  AS YR,
        MONTH(TRY_TO_DATE(pr.PREMIUM_START_DATE::VARCHAR)) AS MO,
        COUNT(DISTINCT po.POLICY_ID)    AS POLICIES_WRITTEN,
        SUM(pr.FINAL_PREMIUM)           AS TOTAL_PREMIUM,
        AVG(pr.DISCOUNT_AMOUNT / NULLIF(pr.BASE_PREMIUM,0)) AS AVG_DISC,
        SUM(pr.DISCOUNT_AMOUNT)         AS TOTAL_DISC,
        SUM(NVL(pr.LATE_FEE,0))         AS TOTAL_LATE
    FROM PNC.PREMIUM pr
    JOIN PNC.POLICY  po ON po.POLICY_ID = pr.POLICY_ID
    WHERE TRY_TO_DATE(pr.PREMIUM_START_DATE::VARCHAR) IS NOT NULL
    GROUP BY 1,2,3
),
new_pol AS (
    SELECT
        AGENT_ID,
        YEAR(TRY_TO_DATE(EFFECTIVE_DATE::VARCHAR))  AS YR,
        MONTH(TRY_TO_DATE(EFFECTIVE_DATE::VARCHAR)) AS MO,
        COUNT(*) AS NEW_POLICIES
    FROM PNC.POLICY
    WHERE TRY_TO_DATE(EFFECTIVE_DATE::VARCHAR) IS NOT NULL
    GROUP BY 1,2,3
)
SELECT
    PNC_DW.SEQ_FACT_AGT_MON_SK.NEXTVAL,
    dag.AGENT_SK,
    pa.YR,
    pa.MO,
    NVL(pa.POLICIES_WRITTEN,0),
    NVL(np.NEW_POLICIES,0),
    NVL(pa.TOTAL_PREMIUM,0),
    pa.AVG_DISC,
    NVL(pa.TOTAL_DISC,0),
    NVL(pa.TOTAL_LATE,0)
FROM prem_agg pa
LEFT JOIN new_pol np    ON np.AGENT_ID = pa.AGENT_ID AND np.YR = pa.YR AND np.MO = pa.MO
LEFT JOIN PNC_DW.DIM_AGENT dag ON dag.AGENT_ID = pa.AGENT_ID;

-- 18. FACT_POLICY_LIFECYCLE
INSERT INTO PNC_DW.FACT_POLICY_LIFECYCLE
    (POLICY_LIFECYCLE_SK, POLICY_SK, POLICYHOLDER_SK, AGENT_SK,
     POLICY_TYPE_SK, DISTRIBUTION_CHAN_SK,
     EFFECTIVE_DATE_SK, EXPIRATION_DATE_SK,
     IS_ACTIVE, IS_EXPIRED, MULTI_POLICY_FLAG,
     POLICY_DURATION_DAYS, ANNUAL_PREMIUM, COVERAGE_LIMIT, DISCOUNT_RATE)
SELECT
    PNC_DW.SEQ_FACT_POL_LIFE_SK.NEXTVAL,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    dp.AGENT_SK,
    dpt.POLICY_TYPE_SK,
    ddc.DISTRIBUTION_CHANNEL_SK,
    de.DATE_SK,
    dx.DATE_SK,
    p.STATUS ILIKE '%active%'                                  AS IS_ACTIVE,
    TRY_TO_DATE(p.EXPIRATION_DATE::VARCHAR) < CURRENT_DATE()   AS IS_EXPIRED,
    p.MULTI_POLICY_FLAG::BOOLEAN,
    DATEDIFF(DAY, TRY_TO_DATE(p.EFFECTIVE_DATE::VARCHAR), TRY_TO_DATE(p.EXPIRATION_DATE::VARCHAR)),
    p.ANNUAL_PREMIUM,
    p.COVERAGE_LIMIT,
    p.DISCOUNT_RATE
FROM PNC.POLICY p
LEFT JOIN PNC_DW.DIM_POLICY              dp  ON dp.POLICY_ID            = p.POLICY_ID
LEFT JOIN PNC_DW.DIM_POLICY_TYPE         dpt ON dpt.POLICY_TYPE          = TRIM(p.POLICY_TYPE)
                                            AND dpt.BUSINESS_TYPE         = TRIM(p.BUSINESS_TYPE)
LEFT JOIN PNC_DW.DIM_DISTRIBUTION_CHANNEL ddc ON ddc.DISTRIBUTION_CHANNEL = TRIM(p.DISTRIBUTION_CHANNEL)
                                              AND ddc.POLICY_TIER           = TRIM(p.POLICY_TIER)
LEFT JOIN PNC_DW.DIM_DATE                de  ON de.FULL_DATE              = TRY_TO_DATE(p.EFFECTIVE_DATE::VARCHAR)
LEFT JOIN PNC_DW.DIM_DATE                dx  ON dx.FULL_DATE              = TRY_TO_DATE(p.EXPIRATION_DATE::VARCHAR);

-- 19. FACT_CLAIM_REINSURANCE_RECOVERY
INSERT INTO PNC_DW.FACT_CLAIM_REINSURANCE_RECOVERY
    (CLAIM_REIN_RECOVERY_SK, CLAIM_ID, REINSURANCE_ID,
     POLICY_SK, REINSURER_SK, DATE_FILED_SK,
     CLAIM_STATUS, TREATY_TYPE, CESSION_PERCENTAGE,
     CLAIM_APPROVED_AMOUNT, CEDED_RECOVERY, RETAINED_AMOUNT)
SELECT
    PNC_DW.SEQ_FACT_REIN_REC_SK.NEXTVAL,
    c.CLAIM_ID,
    r.REINSURANCE_ID,
    dp.POLICY_SK,
    dr.REINSURER_SK,
    dd.DATE_SK,
    c.CLAIM_STATUS,
    r.TREATY_TYPE,
    NVL(r.CESSION_PERCENTAGE,0),
    NVL(c.APPROVED_AMOUNT,0),
    NVL(c.APPROVED_AMOUNT,0) * NVL(r.CESSION_PERCENTAGE,0) / 100.0  AS CEDED_RECOVERY,
    NVL(c.APPROVED_AMOUNT,0) * (1 - NVL(r.CESSION_PERCENTAGE,0) / 100.0) AS RETAINED_AMOUNT
FROM PNC.CLAIM c
JOIN PNC.REINSURANCE r           ON r.POLICY_ID    = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_POLICY   dp ON dp.POLICY_ID   = c.POLICY_ID
LEFT JOIN PNC_DW.DIM_REINSURER dr ON dr.REINSURER_NAME = r.REINSURER_NAME
LEFT JOIN PNC_DW.DIM_DATE     dd ON dd.FULL_DATE    = TRY_TO_DATE(c.DATE_FILED::VARCHAR);

-- 20. FACT_PROPERTY_RISK_EXPOSURE
INSERT INTO PNC_DW.FACT_PROPERTY_RISK_EXPOSURE
    (PROPERTY_RISK_SK, PROPERTY_SK, POLICY_SK, POLICYHOLDER_SK, UNDERWRITER_SK,
     GEOGRAPHY_SK, ASSESSMENT_DATE_SK,
     FLOOD_ZONE, IS_HIGH_FLOOD_RISK, SPRINKLER_SYSTEM, SECURITY_SYSTEM,
     CONSTRUCTION_TYPE, RISK_CATEGORY, CATASTROPHE_EXPOSURE,
     REPLACEMENT_COST, MARKET_VALUE,
     RISK_SCORE, LOSS_PROBABILITY, EXPECTED_LOSS_AMOUNT, RISK_TO_VALUE_RATIO)
SELECT
    PNC_DW.SEQ_FACT_PROP_RISK_SK.NEXTVAL,
    dpr.PROPERTY_SK,
    dp.POLICY_SK,
    dp.POLICYHOLDER_SK,
    du.UNDERWRITER_SK,
    dg.GEOGRAPHY_SK,
    dd.DATE_SK,
    pr.FLOOD_ZONE,
    pr.FLOOD_ZONE ILIKE ANY ('%A%','%V%','%high%')  AS IS_HIGH_FLOOD_RISK,
    pr.SPRINKLER_SYSTEM::BOOLEAN,
    pr.SECURITY_SYSTEM::BOOLEAN,
    pr.CONSTRUCTION_TYPE,
    rp.RISK_CATEGORY,
    rp.CATASTROPHE_EXPOSURE,
    NVL(pr.REPLACEMENT_COST,0),
    NVL(pr.MARKET_VALUE,0),
    rp.RISK_SCORE,
    rp.LOSS_PROBABILITY,
    NVL(rp.EXPECTED_LOSS_AMOUNT,0),
    IFF(pr.REPLACEMENT_COST > 0, NVL(rp.EXPECTED_LOSS_AMOUNT,0) / pr.REPLACEMENT_COST, NULL)
FROM PNC.PROPERTY pr
JOIN PNC.RISK_PROFILE rp              ON rp.POLICY_ID    = pr.POLICY_ID
LEFT JOIN PNC_DW.DIM_PROPERTY  dpr    ON dpr.PROPERTY_ID  = pr.PROPERTY_ID
LEFT JOIN PNC_DW.DIM_POLICY    dp     ON dp.POLICY_ID      = pr.POLICY_ID
LEFT JOIN PNC_DW.DIM_UNDERWRITER du   ON du.UNDERWRITER_ID = rp.UNDERWRITER_ID
LEFT JOIN PNC_DW.DIM_GEOGRAPHY dg     ON dg.STATE_CODE     = UPPER(TRIM(pr.STATE))
LEFT JOIN PNC_DW.DIM_DATE      dd     ON dd.FULL_DATE       = TRY_TO_DATE(rp.ASSESSMENT_DATE::VARCHAR);

-- =============================================================================
-- ANALYTICAL VIEWS
-- =============================================================================

CREATE OR REPLACE VIEW PNC_DW.V_CLAIM_PERFORMANCE AS
SELECT
    d.YEAR,
    d.QUARTER,
    d.MONTH_NAME,
    dph.STATE,
    fc.CLAIM_STATUS,
    fc.SEVERITY,
    dct.CLAIM_TYPE,
    COUNT(*)                                                    AS CLAIM_COUNT,
    SUM(fc.CLAIMED_AMOUNT)                                      AS TOTAL_CLAIMED,
    SUM(fc.APPROVED_AMOUNT)                                     AS TOTAL_APPROVED,
    SUM(fc.TOTAL_PAID_AMOUNT)                                   AS TOTAL_PAID,
    AVG(fc.DAYS_TO_CLOSE)                                       AS AVG_DAYS_TO_CLOSE,
    SUM(CASE WHEN fc.LITIGATION_FLAG  THEN 1 ELSE 0 END)        AS LITIGATION_COUNT,
    SUM(CASE WHEN fc.HAS_FRAUD_INDICATOR THEN 1 ELSE 0 END)     AS FRAUD_FLAG_COUNT,
    AVG(fc.CLAIM_RECOVERY_PCT)                                  AS AVG_RECOVERY_PCT
FROM PNC_DW.FACT_CLAIMS fc
JOIN PNC_DW.DIM_DATE         d   ON d.DATE_SK           = fc.DATE_FILED_SK
JOIN PNC_DW.DIM_POLICYHOLDER dph ON dph.POLICYHOLDER_SK = fc.POLICYHOLDER_SK
LEFT JOIN PNC_DW.DIM_CLAIM_TYPE dct ON dct.CLAIM_TYPE_SK = fc.CLAIM_TYPE_SK
GROUP BY 1,2,3,4,5,6,7;

CREATE OR REPLACE VIEW PNC_DW.V_PREMIUM_SUMMARY AS
SELECT
    d.YEAR,
    d.QUARTER,
    dp.POLICY_TYPE,
    dp.DISTRIBUTION_CHANNEL,
    dp.PAYMENT_FREQUENCY,
    COUNT(*)                                                    AS PREMIUM_RECORDS,
    SUM(fp.BASE_PREMIUM)                                        AS TOTAL_BASE_PREMIUM,
    SUM(fp.DISCOUNT_AMOUNT)                                     AS TOTAL_DISCOUNTS,
    SUM(fp.SURCHARGE_AMOUNT)                                    AS TOTAL_SURCHARGES,
    SUM(fp.FINAL_PREMIUM)                                       AS TOTAL_FINAL_PREMIUM,
    SUM(fp.LATE_FEE)                                            AS TOTAL_LATE_FEES,
    SUM(fp.TOTAL_BILLED)                                        AS TOTAL_BILLED,
    AVG(fp.NET_DISCOUNT_RATE)                                   AS AVG_DISCOUNT_RATE,
    SUM(CASE WHEN fp.AUTOPAY_ENROLLED THEN 1 ELSE 0 END)        AS AUTOPAY_COUNT
FROM PNC_DW.FACT_PREMIUMS fp
JOIN PNC_DW.DIM_DATE   d  ON d.DATE_SK    = fp.PREMIUM_START_DATE_SK
JOIN PNC_DW.DIM_POLICY dp ON dp.POLICY_SK = fp.POLICY_SK
GROUP BY 1,2,3,4,5;

CREATE OR REPLACE VIEW PNC_DW.V_ADJUSTER_SCORECARD AS
SELECT
    da.FULL_NAME                                                AS ADJUSTER_NAME,
    da.ADJUSTER_TYPE,
    da.TERRITORY,
    da.SETTLEMENT_RATE,
    COUNT(fc.CLAIM_SK)                                          AS CLAIMS_HANDLED,
    AVG(fc.DAYS_TO_CLOSE)                                       AS AVG_DAYS_TO_CLOSE,
    SUM(fc.APPROVED_AMOUNT)                                     AS TOTAL_APPROVED,
    AVG(fc.CLAIM_RECOVERY_PCT)                                  AS AVG_RECOVERY_PCT,
    SUM(CASE WHEN fc.LITIGATION_FLAG THEN 1 ELSE 0 END)         AS LITIGATION_COUNT,
    COUNT(DISTINCT fca.ASSESSMENT_ID)                           AS ASSESSMENTS_DONE,
    AVG(fca.HOURS_SPENT)                                        AS AVG_HOURS_PER_ASSESSMENT,
    AVG(fca.REVISION_COUNT)                                     AS AVG_REVISIONS
FROM PNC_DW.DIM_ADJUSTER da
LEFT JOIN PNC_DW.FACT_CLAIMS           fc  ON fc.ADJUSTER_SK  = da.ADJUSTER_SK
LEFT JOIN PNC_DW.FACT_CLAIM_ASSESSMENT fca ON fca.ADJUSTER_SK = da.ADJUSTER_SK
GROUP BY 1,2,3,4;

CREATE OR REPLACE VIEW PNC_DW.V_UNDERWRITING_RISK AS
SELECT
    du.FULL_NAME                                                AS UNDERWRITER_NAME,
    du.SPECIALTY,
    dp.POLICY_TYPE,
    dp.POLICY_TIER,
    fr.RISK_CATEGORY,
    fr.UNDERWRITING_DECISION,
    COUNT(*)                                                    AS POLICIES_ASSESSED,
    AVG(fr.RISK_SCORE)                                          AS AVG_RISK_SCORE,
    AVG(fr.LOSS_PROBABILITY)                                    AS AVG_LOSS_PROBABILITY,
    SUM(fr.EXPECTED_LOSS_AMOUNT)                                AS TOTAL_EXPECTED_LOSS,
    SUM(CASE WHEN fr.PRIOR_CLAIMS_FLAG THEN 1 ELSE 0 END)       AS PRIOR_CLAIMS_COUNT,
    SUM(CASE WHEN fr.HIGH_VALUE_FLAG   THEN 1 ELSE 0 END)       AS HIGH_VALUE_COUNT,
    AVG(fr.RATE_MODIFIER)                                       AS AVG_RATE_MODIFIER
FROM PNC_DW.FACT_RISK_UNDERWRITING fr
JOIN PNC_DW.DIM_UNDERWRITER du ON du.UNDERWRITER_SK = fr.UNDERWRITER_SK
JOIN PNC_DW.DIM_POLICY      dp ON dp.POLICY_SK      = fr.POLICY_SK
GROUP BY 1,2,3,4,5,6;
